// This file was generated by the following script:
//
//   $ /home/brian/src/AceTimeTools/src/acetimetools/tzcompiler.py
//     --input_dir /home/brian/src/AceTime/src/zonedbx/tzfiles
//     --output_dir /home/brian/src/AceTime/src/zonedbx
//     --tz_version 2024a
//     --action zonedb
//     --language arduino
//     --scope extended
//     --db_namespace zonedbx
//     --start_year 2000
//     --until_year 2200
//
// using the TZ Database files
//
//   africa
//   antarctica
//   asia
//   australasia
//   backward
//   etcetera
//   europe
//   northamerica
//   southamerica
//
// from https://github.com/eggert/tz/releases/tag/2024a
//
// Supported Zones: 596 (351 zones, 245 links)
// Unsupported Zones: 0 (0 zones, 0 links)
//
// Requested Years: [2000,2200]
// Accurate Years: [2000,32767]
//
// Original Years:  [1844,2087]
// Generated Years: [1950,2087]
// Lower/Upper Truncated: [True,False]
//
// Estimator Years: [1950,2090]
// Max Buffer Size: 7
//
// Records:
//   Infos: 596
//   Eras: 657
//   Policies: 83
//   Rules: 735
//
// Memory (8-bits):
//   Context: 16
//   Rules: 6615
//   Policies: 249
//   Eras: 7227
//   Zones: 4563
//   Links: 3185
//   Registry: 1192
//   Formats: 597
//   Letters: 46
//   Fragments: 150
//   Names: 5649 (original: 9076)
//   TOTAL: 29489
//
// Memory (32-bits):
//   Context: 24
//   Rules: 8820
//   Policies: 664
//   Eras: 10512
//   Zones: 8424
//   Links: 5880
//   Registry: 2384
//   Formats: 597
//   Letters: 64
//   Fragments: 178
//   Names: 5649 (original: 9076)
//   TOTAL: 43196
//
// DO NOT EDIT

#ifndef ACE_TIME_ZONEDBX_ZONE_REGISTRY_H
#define ACE_TIME_ZONEDBX_ZONE_REGISTRY_H

#include <zoneinfo/infos.h>

namespace ace_time {
namespace zonedbx {

// Zones
const uint16_t kZoneRegistrySize = 351;
extern const extended::ZoneInfo* const kZoneRegistry[351];

// Zones and Links
const uint16_t kZoneAndLinkRegistrySize = 596;
extern const extended::ZoneInfo* const kZoneAndLinkRegistry[596];

}
}
#endif
