// This file was generated by the following script:
//
//  $ ../../../tools/tzcompiler.py --input_dir /home/brian/dev/tz --output_dir /home/brian/dev/AceTime/src/ace_time/zonedb --tz_version 2019a --zonedb --arduino
//
// using the TZ Database files
//
//  africa, antarctica, asia, australasia, europe, northamerica, southamerica
//
// from https://github.com/eggert/tz/releases/tag/2019a
//
// DO NOT EDIT

#ifndef ACE_TIME_ZONEDB_ZONE_POLICIES_H
#define ACE_TIME_ZONEDB_ZONE_POLICIES_H

#include "../common/ZonePolicy.h"

namespace ace_time {
namespace zonedb {

// numPolicies: 64
extern const ZonePolicy kPolicyAN;
extern const ZonePolicy kPolicyAQ;
extern const ZonePolicy kPolicyAS;
extern const ZonePolicy kPolicyAT;
extern const ZonePolicy kPolicyAV;
extern const ZonePolicy kPolicyAW;
extern const ZonePolicy kPolicyArmenia;
extern const ZonePolicy kPolicyAus;
extern const ZonePolicy kPolicyAzer;
extern const ZonePolicy kPolicyBarb;
extern const ZonePolicy kPolicyBrazil;
extern const ZonePolicy kPolicyCO;
extern const ZonePolicy kPolicyCR;
extern const ZonePolicy kPolicyCanada;
extern const ZonePolicy kPolicyChatham;
extern const ZonePolicy kPolicyChile;
extern const ZonePolicy kPolicyCook;
extern const ZonePolicy kPolicyCuba;
extern const ZonePolicy kPolicyDhaka;
extern const ZonePolicy kPolicyEU;
extern const ZonePolicy kPolicyEUAsia;
extern const ZonePolicy kPolicyEcuador;
extern const ZonePolicy kPolicyEire;
extern const ZonePolicy kPolicyFiji;
extern const ZonePolicy kPolicyGhana;
extern const ZonePolicy kPolicyGuat;
extern const ZonePolicy kPolicyHK;
extern const ZonePolicy kPolicyHaiti;
extern const ZonePolicy kPolicyHoliday;
extern const ZonePolicy kPolicyHond;
extern const ZonePolicy kPolicyIran;
extern const ZonePolicy kPolicyIraq;
extern const ZonePolicy kPolicyJapan;
extern const ZonePolicy kPolicyJordan;
extern const ZonePolicy kPolicyLH;
extern const ZonePolicy kPolicyLebanon;
extern const ZonePolicy kPolicyMacau;
extern const ZonePolicy kPolicyMauritius;
extern const ZonePolicy kPolicyMexico;
extern const ZonePolicy kPolicyMoldova;
extern const ZonePolicy kPolicyMoncton;
extern const ZonePolicy kPolicyMongol;
extern const ZonePolicy kPolicyNC;
extern const ZonePolicy kPolicyNZ;
extern const ZonePolicy kPolicyNic;
extern const ZonePolicy kPolicyPRC;
extern const ZonePolicy kPolicyPakistan;
extern const ZonePolicy kPolicyPara;
extern const ZonePolicy kPolicyPeru;
extern const ZonePolicy kPolicyPhil;
extern const ZonePolicy kPolicyROK;
extern const ZonePolicy kPolicyRussiaAsia;
extern const ZonePolicy kPolicySA;
extern const ZonePolicy kPolicySalv;
extern const ZonePolicy kPolicySyria;
extern const ZonePolicy kPolicyTaiwan;
extern const ZonePolicy kPolicyThule;
extern const ZonePolicy kPolicyTonga;
extern const ZonePolicy kPolicyTunisia;
extern const ZonePolicy kPolicyUS;
extern const ZonePolicy kPolicyUruguay;
extern const ZonePolicy kPolicyVanuatu;
extern const ZonePolicy kPolicyWinn;
extern const ZonePolicy kPolicyZion;


// The following zone policies are not supported in this database.
//
// numPolicies: 75
//
// kPolicyAlbania (unused)
// kPolicyAlgeria (unused)
// kPolicyArg (unused)
// kPolicyAustria (unused)
// kPolicyBahamas (unused)
// kPolicyBelgium (unused)
// kPolicyBelize (LETTER 'CST' too long)
// kPolicyBulg (unused)
// kPolicyC-Eur (unused)
// kPolicyCA (unused)
// kPolicyChicago (unused)
// kPolicyCyprus (unused)
// kPolicyCzech (unused)
// kPolicyDR (unused)
// kPolicyDenmark (unused)
// kPolicyDenver (unused)
// kPolicyDetroit (unused)
// kPolicyE-Eur (unused)
// kPolicyE-EurAsia (unused)
// kPolicyEdm (unused)
// kPolicyEgypt (Found 2 transitions in year/month '2010-09')
// kPolicyEgyptAsia (unused)
// kPolicyFalk (unused)
// kPolicyFinland (unused)
// kPolicyFrance (unused)
// kPolicyGB-Eire (unused)
// kPolicyGermany (unused)
// kPolicyGreece (unused)
// kPolicyGuam (unused)
// kPolicyHalifax (unused)
// kPolicyHungary (unused)
// kPolicyIceland (unused)
// kPolicyIndianapolis (unused)
// kPolicyItaly (unused)
// kPolicyKyrgyz (unused)
// kPolicyLatvia (unused)
// kPolicyLibya (unused)
// kPolicyLouisville (unused)
// kPolicyLux (unused)
// kPolicyMalta (unused)
// kPolicyMarengo (unused)
// kPolicyMenominee (unused)
// kPolicyMorocco (unused)
// kPolicyNBorneo (unused)
// kPolicyNT_YK (unused)
// kPolicyNYC (unused)
// kPolicyNamibia (LETTER 'WAT' too long)
// kPolicyNeth (unused)
// kPolicyNorway (unused)
// kPolicyPalestine (Found 2 transitions in year/month '2011-08')
// kPolicyPerry (unused)
// kPolicyPike (unused)
// kPolicyPoland (unused)
// kPolicyPort (unused)
// kPolicyPulaski (unused)
// kPolicyRegina (unused)
// kPolicyRomania (unused)
// kPolicyRussia (unused)
// kPolicySanLuis (unused)
// kPolicyShang (unused)
// kPolicySovietZone (unused)
// kPolicySpain (unused)
// kPolicySpainAfrica (unused)
// kPolicyStJohns (unused)
// kPolicyStarke (unused)
// kPolicySudan (unused)
// kPolicySwift (unused)
// kPolicySwiss (unused)
// kPolicyToronto (unused)
// kPolicyTroll (unused)
// kPolicyTurkey (unused)
// kPolicyVanc (unused)
// kPolicyVincennes (unused)
// kPolicyW-Eur (unused)
// kPolicyWS (unused)


// The following zone policies may have inaccuracies due to the following
// reasons:
//
// numPolicies: 1
//
// kPolicyMoncton (AT time '0:01' truncated to '900' seconds)


}
}

#endif
