// This file was generated by the following script:
//
//   $ /home/brian/src/AceTimeTools/src/acetimetools/tzcompiler.py
//     --input_dir /home/brian/dev/tz
//     --output_dir /home/brian/src/AceTime/src/ace_time/zonedb
//     --tz_version 2022g
//     --action zonedb
//     --language arduino
//     --scope basic
//     --generate_int16_years
//     --start_year 2000
//     --until_year 10000
//
// using the TZ Database files
//
//   africa
//   antarctica
//   asia
//   australasia
//   backward
//   etcetera
//   europe
//   northamerica
//   southamerica
//
// from https://github.com/eggert/tz/releases/tag/2022g
//
// DO NOT EDIT

#ifndef ACE_TIME_ZONEDB_ZONE_REGISTRY_H
#define ACE_TIME_ZONEDB_ZONE_REGISTRY_H

#include <ace_time/internal/ZoneInfo.h>
#include <ace_time/internal/LinkEntry.h>

namespace ace_time {
namespace zonedb {

// Zones
const uint16_t kZoneRegistrySize = 227;
extern const basic::ZoneInfo* const kZoneRegistry[227];

// Zones and Links
const uint16_t kZoneAndLinkRegistrySize = 446;
extern const basic::ZoneInfo* const kZoneAndLinkRegistry[446];

// Link Entries
const uint16_t kLinkRegistrySize = 219;
extern const basic::LinkEntry kLinkRegistry[219];

}
}
#endif
