// This file was generated by the following script:
//
//  $ ../../../tools/tzcompiler.py --input_dir /home/brian/dev/tz --output_dir /home/brian/dev/AceTime/src/ace_time/zonedb --tz_version 2018i --zonedb --arduino --granularity 900
//
// using the TZ Database files
//
//  africa, antarctica, asia, australasia, europe, northamerica, southamerica
//
// from https://github.com/eggert/tz/releases/tag/2018i
//
// DO NOT EDIT

#ifndef ACE_TIME_ZONE_INFOS_H
#define ACE_TIME_ZONE_INFOS_H

#include "ZoneInfo.h"

#define ACE_TIME_TZ_DATABASE_VERSION "2018i"

namespace ace_time {
namespace zonedb {

// numInfos: 341
extern const ZoneInfo kZoneAbidjan; // Africa/Abidjan
extern const ZoneInfo kZoneAccra; // Africa/Accra
extern const ZoneInfo kZoneAlgiers; // Africa/Algiers
extern const ZoneInfo kZoneBissau; // Africa/Bissau
extern const ZoneInfo kZoneCairo; // Africa/Cairo
extern const ZoneInfo kZoneCasablanca; // Africa/Casablanca
extern const ZoneInfo kZoneCeuta; // Africa/Ceuta
extern const ZoneInfo kZoneEl_Aaiun; // Africa/El_Aaiun
extern const ZoneInfo kZoneJohannesburg; // Africa/Johannesburg
extern const ZoneInfo kZoneJuba; // Africa/Juba
extern const ZoneInfo kZoneKhartoum; // Africa/Khartoum
extern const ZoneInfo kZoneLagos; // Africa/Lagos
extern const ZoneInfo kZoneMaputo; // Africa/Maputo
extern const ZoneInfo kZoneMonrovia; // Africa/Monrovia
extern const ZoneInfo kZoneNairobi; // Africa/Nairobi
extern const ZoneInfo kZoneNdjamena; // Africa/Ndjamena
extern const ZoneInfo kZoneSao_Tome; // Africa/Sao_Tome
extern const ZoneInfo kZoneTripoli; // Africa/Tripoli
extern const ZoneInfo kZoneTunis; // Africa/Tunis
extern const ZoneInfo kZoneAdak; // America/Adak
extern const ZoneInfo kZoneAnchorage; // America/Anchorage
extern const ZoneInfo kZoneAraguaina; // America/Araguaina
extern const ZoneInfo kZoneBuenos_Aires; // America/Argentina/Buenos_Aires
extern const ZoneInfo kZoneCatamarca; // America/Argentina/Catamarca
extern const ZoneInfo kZoneCordoba; // America/Argentina/Cordoba
extern const ZoneInfo kZoneJujuy; // America/Argentina/Jujuy
extern const ZoneInfo kZoneLa_Rioja; // America/Argentina/La_Rioja
extern const ZoneInfo kZoneMendoza; // America/Argentina/Mendoza
extern const ZoneInfo kZoneRio_Gallegos; // America/Argentina/Rio_Gallegos
extern const ZoneInfo kZoneSalta; // America/Argentina/Salta
extern const ZoneInfo kZoneSan_Juan; // America/Argentina/San_Juan
extern const ZoneInfo kZoneTucuman; // America/Argentina/Tucuman
extern const ZoneInfo kZoneUshuaia; // America/Argentina/Ushuaia
extern const ZoneInfo kZoneAsuncion; // America/Asuncion
extern const ZoneInfo kZoneAtikokan; // America/Atikokan
extern const ZoneInfo kZoneBahia; // America/Bahia
extern const ZoneInfo kZoneBahia_Banderas; // America/Bahia_Banderas
extern const ZoneInfo kZoneBarbados; // America/Barbados
extern const ZoneInfo kZoneBelem; // America/Belem
extern const ZoneInfo kZoneBlanc_Sablon; // America/Blanc-Sablon
extern const ZoneInfo kZoneBoa_Vista; // America/Boa_Vista
extern const ZoneInfo kZoneBogota; // America/Bogota
extern const ZoneInfo kZoneBoise; // America/Boise
extern const ZoneInfo kZoneCambridge_Bay; // America/Cambridge_Bay
extern const ZoneInfo kZoneCampo_Grande; // America/Campo_Grande
extern const ZoneInfo kZoneCancun; // America/Cancun
extern const ZoneInfo kZoneCaracas; // America/Caracas
extern const ZoneInfo kZoneCayenne; // America/Cayenne
extern const ZoneInfo kZoneChicago; // America/Chicago
extern const ZoneInfo kZoneChihuahua; // America/Chihuahua
extern const ZoneInfo kZoneCosta_Rica; // America/Costa_Rica
extern const ZoneInfo kZoneCreston; // America/Creston
extern const ZoneInfo kZoneCuiaba; // America/Cuiaba
extern const ZoneInfo kZoneCuracao; // America/Curacao
extern const ZoneInfo kZoneDanmarkshavn; // America/Danmarkshavn
extern const ZoneInfo kZoneDawson; // America/Dawson
extern const ZoneInfo kZoneDawson_Creek; // America/Dawson_Creek
extern const ZoneInfo kZoneDenver; // America/Denver
extern const ZoneInfo kZoneDetroit; // America/Detroit
extern const ZoneInfo kZoneEdmonton; // America/Edmonton
extern const ZoneInfo kZoneEirunepe; // America/Eirunepe
extern const ZoneInfo kZoneEl_Salvador; // America/El_Salvador
extern const ZoneInfo kZoneFort_Nelson; // America/Fort_Nelson
extern const ZoneInfo kZoneFortaleza; // America/Fortaleza
extern const ZoneInfo kZoneGlace_Bay; // America/Glace_Bay
extern const ZoneInfo kZoneGodthab; // America/Godthab
extern const ZoneInfo kZoneGrand_Turk; // America/Grand_Turk
extern const ZoneInfo kZoneGuatemala; // America/Guatemala
extern const ZoneInfo kZoneGuayaquil; // America/Guayaquil
extern const ZoneInfo kZoneGuyana; // America/Guyana
extern const ZoneInfo kZoneHalifax; // America/Halifax
extern const ZoneInfo kZoneHavana; // America/Havana
extern const ZoneInfo kZoneHermosillo; // America/Hermosillo
extern const ZoneInfo kZoneIndianapolis; // America/Indiana/Indianapolis
extern const ZoneInfo kZoneKnox; // America/Indiana/Knox
extern const ZoneInfo kZoneMarengo; // America/Indiana/Marengo
extern const ZoneInfo kZonePetersburg; // America/Indiana/Petersburg
extern const ZoneInfo kZoneTell_City; // America/Indiana/Tell_City
extern const ZoneInfo kZoneVevay; // America/Indiana/Vevay
extern const ZoneInfo kZoneVincennes; // America/Indiana/Vincennes
extern const ZoneInfo kZoneWinamac; // America/Indiana/Winamac
extern const ZoneInfo kZoneInuvik; // America/Inuvik
extern const ZoneInfo kZoneIqaluit; // America/Iqaluit
extern const ZoneInfo kZoneJamaica; // America/Jamaica
extern const ZoneInfo kZoneJuneau; // America/Juneau
extern const ZoneInfo kZoneLouisville; // America/Kentucky/Louisville
extern const ZoneInfo kZoneMonticello; // America/Kentucky/Monticello
extern const ZoneInfo kZoneLa_Paz; // America/La_Paz
extern const ZoneInfo kZoneLima; // America/Lima
extern const ZoneInfo kZoneLos_Angeles; // America/Los_Angeles
extern const ZoneInfo kZoneMaceio; // America/Maceio
extern const ZoneInfo kZoneManagua; // America/Managua
extern const ZoneInfo kZoneManaus; // America/Manaus
extern const ZoneInfo kZoneMartinique; // America/Martinique
extern const ZoneInfo kZoneMatamoros; // America/Matamoros
extern const ZoneInfo kZoneMazatlan; // America/Mazatlan
extern const ZoneInfo kZoneMenominee; // America/Menominee
extern const ZoneInfo kZoneMerida; // America/Merida
extern const ZoneInfo kZoneMetlakatla; // America/Metlakatla
extern const ZoneInfo kZoneMexico_City; // America/Mexico_City
extern const ZoneInfo kZoneMiquelon; // America/Miquelon
extern const ZoneInfo kZoneMoncton; // America/Moncton
extern const ZoneInfo kZoneMonterrey; // America/Monterrey
extern const ZoneInfo kZoneMontevideo; // America/Montevideo
extern const ZoneInfo kZoneNassau; // America/Nassau
extern const ZoneInfo kZoneNew_York; // America/New_York
extern const ZoneInfo kZoneNipigon; // America/Nipigon
extern const ZoneInfo kZoneNome; // America/Nome
extern const ZoneInfo kZoneNoronha; // America/Noronha
extern const ZoneInfo kZoneBeulah; // America/North_Dakota/Beulah
extern const ZoneInfo kZoneCenter; // America/North_Dakota/Center
extern const ZoneInfo kZoneNew_Salem; // America/North_Dakota/New_Salem
extern const ZoneInfo kZoneOjinaga; // America/Ojinaga
extern const ZoneInfo kZonePanama; // America/Panama
extern const ZoneInfo kZonePangnirtung; // America/Pangnirtung
extern const ZoneInfo kZoneParamaribo; // America/Paramaribo
extern const ZoneInfo kZonePhoenix; // America/Phoenix
extern const ZoneInfo kZonePort_au_Prince; // America/Port-au-Prince
extern const ZoneInfo kZonePort_of_Spain; // America/Port_of_Spain
extern const ZoneInfo kZonePorto_Velho; // America/Porto_Velho
extern const ZoneInfo kZonePuerto_Rico; // America/Puerto_Rico
extern const ZoneInfo kZonePunta_Arenas; // America/Punta_Arenas
extern const ZoneInfo kZoneRainy_River; // America/Rainy_River
extern const ZoneInfo kZoneRankin_Inlet; // America/Rankin_Inlet
extern const ZoneInfo kZoneRecife; // America/Recife
extern const ZoneInfo kZoneRegina; // America/Regina
extern const ZoneInfo kZoneResolute; // America/Resolute
extern const ZoneInfo kZoneRio_Branco; // America/Rio_Branco
extern const ZoneInfo kZoneSantarem; // America/Santarem
extern const ZoneInfo kZoneSantiago; // America/Santiago
extern const ZoneInfo kZoneSanto_Domingo; // America/Santo_Domingo
extern const ZoneInfo kZoneSao_Paulo; // America/Sao_Paulo
extern const ZoneInfo kZoneScoresbysund; // America/Scoresbysund
extern const ZoneInfo kZoneSitka; // America/Sitka
extern const ZoneInfo kZoneSwift_Current; // America/Swift_Current
extern const ZoneInfo kZoneTegucigalpa; // America/Tegucigalpa
extern const ZoneInfo kZoneThule; // America/Thule
extern const ZoneInfo kZoneThunder_Bay; // America/Thunder_Bay
extern const ZoneInfo kZoneTijuana; // America/Tijuana
extern const ZoneInfo kZoneToronto; // America/Toronto
extern const ZoneInfo kZoneVancouver; // America/Vancouver
extern const ZoneInfo kZoneWhitehorse; // America/Whitehorse
extern const ZoneInfo kZoneWinnipeg; // America/Winnipeg
extern const ZoneInfo kZoneYakutat; // America/Yakutat
extern const ZoneInfo kZoneYellowknife; // America/Yellowknife
extern const ZoneInfo kZoneCasey; // Antarctica/Casey
extern const ZoneInfo kZoneDavis; // Antarctica/Davis
extern const ZoneInfo kZoneDumontDUrville; // Antarctica/DumontDUrville
extern const ZoneInfo kZoneMacquarie; // Antarctica/Macquarie
extern const ZoneInfo kZoneMawson; // Antarctica/Mawson
extern const ZoneInfo kZonePalmer; // Antarctica/Palmer
extern const ZoneInfo kZoneRothera; // Antarctica/Rothera
extern const ZoneInfo kZoneSyowa; // Antarctica/Syowa
extern const ZoneInfo kZoneVostok; // Antarctica/Vostok
extern const ZoneInfo kZoneAlmaty; // Asia/Almaty
extern const ZoneInfo kZoneAmman; // Asia/Amman
extern const ZoneInfo kZoneAnadyr; // Asia/Anadyr
extern const ZoneInfo kZoneAqtau; // Asia/Aqtau
extern const ZoneInfo kZoneAqtobe; // Asia/Aqtobe
extern const ZoneInfo kZoneAshgabat; // Asia/Ashgabat
extern const ZoneInfo kZoneAtyrau; // Asia/Atyrau
extern const ZoneInfo kZoneBaghdad; // Asia/Baghdad
extern const ZoneInfo kZoneBaku; // Asia/Baku
extern const ZoneInfo kZoneBangkok; // Asia/Bangkok
extern const ZoneInfo kZoneBarnaul; // Asia/Barnaul
extern const ZoneInfo kZoneBeirut; // Asia/Beirut
extern const ZoneInfo kZoneBishkek; // Asia/Bishkek
extern const ZoneInfo kZoneBrunei; // Asia/Brunei
extern const ZoneInfo kZoneChita; // Asia/Chita
extern const ZoneInfo kZoneChoibalsan; // Asia/Choibalsan
extern const ZoneInfo kZoneColombo; // Asia/Colombo
extern const ZoneInfo kZoneDamascus; // Asia/Damascus
extern const ZoneInfo kZoneDhaka; // Asia/Dhaka
extern const ZoneInfo kZoneDili; // Asia/Dili
extern const ZoneInfo kZoneDubai; // Asia/Dubai
extern const ZoneInfo kZoneDushanbe; // Asia/Dushanbe
extern const ZoneInfo kZoneFamagusta; // Asia/Famagusta
extern const ZoneInfo kZoneGaza; // Asia/Gaza
extern const ZoneInfo kZoneHebron; // Asia/Hebron
extern const ZoneInfo kZoneHo_Chi_Minh; // Asia/Ho_Chi_Minh
extern const ZoneInfo kZoneHong_Kong; // Asia/Hong_Kong
extern const ZoneInfo kZoneHovd; // Asia/Hovd
extern const ZoneInfo kZoneIrkutsk; // Asia/Irkutsk
extern const ZoneInfo kZoneJakarta; // Asia/Jakarta
extern const ZoneInfo kZoneJayapura; // Asia/Jayapura
extern const ZoneInfo kZoneJerusalem; // Asia/Jerusalem
extern const ZoneInfo kZoneKabul; // Asia/Kabul
extern const ZoneInfo kZoneKamchatka; // Asia/Kamchatka
extern const ZoneInfo kZoneKarachi; // Asia/Karachi
extern const ZoneInfo kZoneKathmandu; // Asia/Kathmandu
extern const ZoneInfo kZoneKhandyga; // Asia/Khandyga
extern const ZoneInfo kZoneKolkata; // Asia/Kolkata
extern const ZoneInfo kZoneKrasnoyarsk; // Asia/Krasnoyarsk
extern const ZoneInfo kZoneKuala_Lumpur; // Asia/Kuala_Lumpur
extern const ZoneInfo kZoneKuching; // Asia/Kuching
extern const ZoneInfo kZoneMacau; // Asia/Macau
extern const ZoneInfo kZoneMagadan; // Asia/Magadan
extern const ZoneInfo kZoneMakassar; // Asia/Makassar
extern const ZoneInfo kZoneManila; // Asia/Manila
extern const ZoneInfo kZoneNicosia; // Asia/Nicosia
extern const ZoneInfo kZoneNovokuznetsk; // Asia/Novokuznetsk
extern const ZoneInfo kZoneNovosibirsk; // Asia/Novosibirsk
extern const ZoneInfo kZoneOmsk; // Asia/Omsk
extern const ZoneInfo kZoneOral; // Asia/Oral
extern const ZoneInfo kZonePontianak; // Asia/Pontianak
extern const ZoneInfo kZonePyongyang; // Asia/Pyongyang
extern const ZoneInfo kZoneQatar; // Asia/Qatar
extern const ZoneInfo kZoneQostanay; // Asia/Qostanay
extern const ZoneInfo kZoneQyzylorda; // Asia/Qyzylorda
extern const ZoneInfo kZoneRiyadh; // Asia/Riyadh
extern const ZoneInfo kZoneSakhalin; // Asia/Sakhalin
extern const ZoneInfo kZoneSamarkand; // Asia/Samarkand
extern const ZoneInfo kZoneSeoul; // Asia/Seoul
extern const ZoneInfo kZoneShanghai; // Asia/Shanghai
extern const ZoneInfo kZoneSingapore; // Asia/Singapore
extern const ZoneInfo kZoneSrednekolymsk; // Asia/Srednekolymsk
extern const ZoneInfo kZoneTaipei; // Asia/Taipei
extern const ZoneInfo kZoneTashkent; // Asia/Tashkent
extern const ZoneInfo kZoneTbilisi; // Asia/Tbilisi
extern const ZoneInfo kZoneTehran; // Asia/Tehran
extern const ZoneInfo kZoneThimphu; // Asia/Thimphu
extern const ZoneInfo kZoneTokyo; // Asia/Tokyo
extern const ZoneInfo kZoneTomsk; // Asia/Tomsk
extern const ZoneInfo kZoneUlaanbaatar; // Asia/Ulaanbaatar
extern const ZoneInfo kZoneUrumqi; // Asia/Urumqi
extern const ZoneInfo kZoneUst_Nera; // Asia/Ust-Nera
extern const ZoneInfo kZoneVladivostok; // Asia/Vladivostok
extern const ZoneInfo kZoneYakutsk; // Asia/Yakutsk
extern const ZoneInfo kZoneYangon; // Asia/Yangon
extern const ZoneInfo kZoneYekaterinburg; // Asia/Yekaterinburg
extern const ZoneInfo kZoneYerevan; // Asia/Yerevan
extern const ZoneInfo kZoneAzores; // Atlantic/Azores
extern const ZoneInfo kZoneBermuda; // Atlantic/Bermuda
extern const ZoneInfo kZoneCanary; // Atlantic/Canary
extern const ZoneInfo kZoneCape_Verde; // Atlantic/Cape_Verde
extern const ZoneInfo kZoneFaroe; // Atlantic/Faroe
extern const ZoneInfo kZoneMadeira; // Atlantic/Madeira
extern const ZoneInfo kZoneReykjavik; // Atlantic/Reykjavik
extern const ZoneInfo kZoneSouth_Georgia; // Atlantic/South_Georgia
extern const ZoneInfo kZoneStanley; // Atlantic/Stanley
extern const ZoneInfo kZoneAdelaide; // Australia/Adelaide
extern const ZoneInfo kZoneBrisbane; // Australia/Brisbane
extern const ZoneInfo kZoneBroken_Hill; // Australia/Broken_Hill
extern const ZoneInfo kZoneCurrie; // Australia/Currie
extern const ZoneInfo kZoneDarwin; // Australia/Darwin
extern const ZoneInfo kZoneEucla; // Australia/Eucla
extern const ZoneInfo kZoneHobart; // Australia/Hobart
extern const ZoneInfo kZoneLindeman; // Australia/Lindeman
extern const ZoneInfo kZoneLord_Howe; // Australia/Lord_Howe
extern const ZoneInfo kZoneMelbourne; // Australia/Melbourne
extern const ZoneInfo kZonePerth; // Australia/Perth
extern const ZoneInfo kZoneSydney; // Australia/Sydney
extern const ZoneInfo kZoneAmsterdam; // Europe/Amsterdam
extern const ZoneInfo kZoneAndorra; // Europe/Andorra
extern const ZoneInfo kZoneAstrakhan; // Europe/Astrakhan
extern const ZoneInfo kZoneAthens; // Europe/Athens
extern const ZoneInfo kZoneBelgrade; // Europe/Belgrade
extern const ZoneInfo kZoneBerlin; // Europe/Berlin
extern const ZoneInfo kZoneBrussels; // Europe/Brussels
extern const ZoneInfo kZoneBucharest; // Europe/Bucharest
extern const ZoneInfo kZoneBudapest; // Europe/Budapest
extern const ZoneInfo kZoneChisinau; // Europe/Chisinau
extern const ZoneInfo kZoneCopenhagen; // Europe/Copenhagen
extern const ZoneInfo kZoneDublin; // Europe/Dublin
extern const ZoneInfo kZoneGibraltar; // Europe/Gibraltar
extern const ZoneInfo kZoneHelsinki; // Europe/Helsinki
extern const ZoneInfo kZoneKaliningrad; // Europe/Kaliningrad
extern const ZoneInfo kZoneKiev; // Europe/Kiev
extern const ZoneInfo kZoneKirov; // Europe/Kirov
extern const ZoneInfo kZoneLisbon; // Europe/Lisbon
extern const ZoneInfo kZoneLondon; // Europe/London
extern const ZoneInfo kZoneLuxembourg; // Europe/Luxembourg
extern const ZoneInfo kZoneMadrid; // Europe/Madrid
extern const ZoneInfo kZoneMalta; // Europe/Malta
extern const ZoneInfo kZoneMinsk; // Europe/Minsk
extern const ZoneInfo kZoneMonaco; // Europe/Monaco
extern const ZoneInfo kZoneMoscow; // Europe/Moscow
extern const ZoneInfo kZoneOslo; // Europe/Oslo
extern const ZoneInfo kZoneParis; // Europe/Paris
extern const ZoneInfo kZonePrague; // Europe/Prague
extern const ZoneInfo kZoneRiga; // Europe/Riga
extern const ZoneInfo kZoneRome; // Europe/Rome
extern const ZoneInfo kZoneSamara; // Europe/Samara
extern const ZoneInfo kZoneSaratov; // Europe/Saratov
extern const ZoneInfo kZoneSimferopol; // Europe/Simferopol
extern const ZoneInfo kZoneSofia; // Europe/Sofia
extern const ZoneInfo kZoneStockholm; // Europe/Stockholm
extern const ZoneInfo kZoneTallinn; // Europe/Tallinn
extern const ZoneInfo kZoneTirane; // Europe/Tirane
extern const ZoneInfo kZoneUlyanovsk; // Europe/Ulyanovsk
extern const ZoneInfo kZoneUzhgorod; // Europe/Uzhgorod
extern const ZoneInfo kZoneVienna; // Europe/Vienna
extern const ZoneInfo kZoneVilnius; // Europe/Vilnius
extern const ZoneInfo kZoneVolgograd; // Europe/Volgograd
extern const ZoneInfo kZoneWarsaw; // Europe/Warsaw
extern const ZoneInfo kZoneZaporozhye; // Europe/Zaporozhye
extern const ZoneInfo kZoneZurich; // Europe/Zurich
extern const ZoneInfo kZoneChagos; // Indian/Chagos
extern const ZoneInfo kZoneChristmas; // Indian/Christmas
extern const ZoneInfo kZoneCocos; // Indian/Cocos
extern const ZoneInfo kZoneKerguelen; // Indian/Kerguelen
extern const ZoneInfo kZoneMahe; // Indian/Mahe
extern const ZoneInfo kZoneMaldives; // Indian/Maldives
extern const ZoneInfo kZoneMauritius; // Indian/Mauritius
extern const ZoneInfo kZoneReunion; // Indian/Reunion
extern const ZoneInfo kZoneApia; // Pacific/Apia
extern const ZoneInfo kZoneAuckland; // Pacific/Auckland
extern const ZoneInfo kZoneBougainville; // Pacific/Bougainville
extern const ZoneInfo kZoneChatham; // Pacific/Chatham
extern const ZoneInfo kZoneChuuk; // Pacific/Chuuk
extern const ZoneInfo kZoneEaster; // Pacific/Easter
extern const ZoneInfo kZoneEfate; // Pacific/Efate
extern const ZoneInfo kZoneEnderbury; // Pacific/Enderbury
extern const ZoneInfo kZoneFakaofo; // Pacific/Fakaofo
extern const ZoneInfo kZoneFiji; // Pacific/Fiji
extern const ZoneInfo kZoneFunafuti; // Pacific/Funafuti
extern const ZoneInfo kZoneGalapagos; // Pacific/Galapagos
extern const ZoneInfo kZoneGambier; // Pacific/Gambier
extern const ZoneInfo kZoneGuadalcanal; // Pacific/Guadalcanal
extern const ZoneInfo kZoneGuam; // Pacific/Guam
extern const ZoneInfo kZoneHonolulu; // Pacific/Honolulu
extern const ZoneInfo kZoneKiritimati; // Pacific/Kiritimati
extern const ZoneInfo kZoneKosrae; // Pacific/Kosrae
extern const ZoneInfo kZoneKwajalein; // Pacific/Kwajalein
extern const ZoneInfo kZoneMajuro; // Pacific/Majuro
extern const ZoneInfo kZoneMarquesas; // Pacific/Marquesas
extern const ZoneInfo kZoneNauru; // Pacific/Nauru
extern const ZoneInfo kZoneNiue; // Pacific/Niue
extern const ZoneInfo kZoneNorfolk; // Pacific/Norfolk
extern const ZoneInfo kZoneNoumea; // Pacific/Noumea
extern const ZoneInfo kZonePago_Pago; // Pacific/Pago_Pago
extern const ZoneInfo kZonePalau; // Pacific/Palau
extern const ZoneInfo kZonePitcairn; // Pacific/Pitcairn
extern const ZoneInfo kZonePohnpei; // Pacific/Pohnpei
extern const ZoneInfo kZonePort_Moresby; // Pacific/Port_Moresby
extern const ZoneInfo kZoneRarotonga; // Pacific/Rarotonga
extern const ZoneInfo kZoneTahiti; // Pacific/Tahiti
extern const ZoneInfo kZoneTarawa; // Pacific/Tarawa
extern const ZoneInfo kZoneTongatapu; // Pacific/Tongatapu
extern const ZoneInfo kZoneWake; // Pacific/Wake
extern const ZoneInfo kZoneWallis; // Pacific/Wallis


// The following zones are not supported in the current version of AceTime.
//
// numInfos: 18
//
// Africa/Windhoek (rule 'Namibia' not found)
// America/Argentina/San_Luis (offset in RULES '1:00')
// America/Belize (rule 'Belize' not found)
// America/Goose_Bay (rule 'StJohns' not found)
// America/St_Johns (rule 'StJohns' not found)
// Antarctica/Troll (rule 'Troll' not found)
// CET (no '/' in zone name)
// CST6CDT (no '/' in zone name)
// EET (no '/' in zone name)
// EST (no '/' in zone name)
// EST5EDT (no '/' in zone name)
// Europe/Istanbul (offset in RULES '1:00')
// HST (no '/' in zone name)
// MET (no '/' in zone name)
// MST (no '/' in zone name)
// MST7MDT (no '/' in zone name)
// PST8PDT (no '/' in zone name)
// WET (no '/' in zone name)


// The following zones may have inaccuracies due to the following reasons:
//
// numInfos: 1
//
// Asia/Gaza (UNTIL time '0:01' truncated to '900' seconds)


}
}

#endif
