TARGETS := zone_infos.cpp zone_infos.h zone_policies.cpp zone_policies.h zone_strings.cpp zone_strings.h

all:
	../../../tools/tzcompiler.sh --tag 2019a --action zonedb --language arduino --scope extended --start_year 2000 --until_year 2050
