// This file was generated by the following script:
//
//   $ /home/brian/src/AceTimeTools/src/acetimetools/tzcompiler.py
//     --input_dir /home/brian/src/AceTime/src/ace_time/zonedbx/tzfiles
//     --output_dir /home/brian/src/AceTime/src/ace_time/zonedbx
//     --tz_version 2022g
//     --action zonedb
//     --language arduino
//     --scope extended
//     --generate_int16_years
//     --start_year 2000
//     --until_year 10000
//
// using the TZ Database files
//
//   africa
//   antarctica
//   asia
//   australasia
//   backward
//   etcetera
//   europe
//   northamerica
//   southamerica
//
// from https://github.com/eggert/tz/releases/tag/2022g
//
// DO NOT EDIT

#ifndef ACE_TIME_ZONEDBX_ZONE_REGISTRY_H
#define ACE_TIME_ZONEDBX_ZONE_REGISTRY_H

#include <ace_time/internal/ZoneInfo.h>
#include <ace_time/internal/LinkEntry.h>

namespace ace_time {
namespace zonedbx {

// Zones
const uint16_t kZoneRegistrySize = 351;
extern const extended::ZoneInfo* const kZoneRegistry[351];

// Zones and Links
const uint16_t kZoneAndLinkRegistrySize = 596;
extern const extended::ZoneInfo* const kZoneAndLinkRegistry[596];

// Link Entries
const uint16_t kLinkRegistrySize = 245;
extern const extended::LinkEntry kLinkRegistry[245];

}
}
#endif
