// This file was generated by the following script:
//
//   $ ../../../tools/tzcompiler.py --input_dir /home/brian/dev/tz --output_dir /home/brian/dev/AceTime/src/ace_time/zonedbx --tz_version 2019a --zonedb --arduino_extended
//
// using the TZ Database files from
// https://github.com/eggert/tz/releases/tag/2019a
//
// DO NOT EDIT

#ifndef ACE_TIME_ZONEDBX_ZONE_STRINGS_H
#define ACE_TIME_ZONEDBX_ZONE_STRINGS_H

namespace ace_time {
namespace zonedbx {

extern const char* const kFormats[];

extern const char* const kZoneStrings[];

}
}
#endif
