// This file was generated by the following script:
//
//  $ ../../../tools/tzcompiler.py --input_dir ../../../tools/../../tz --output_dir /home/brian/dev/AceTime/src/ace_time/zonedbx --tz_version 2019b --action zonedb --language arduino --scope extended --start_year 2000 --until_year 2050
//
// using the TZ Database files
//
//  africa, antarctica, asia, australasia, backward, etcetera, europe, northamerica, southamerica
//
// from https://github.com/eggert/tz/releases/tag/2019b
//
// DO NOT EDIT

#ifndef ACE_TIME_ZONEDBX_ZONE_INFOS_H
#define ACE_TIME_ZONEDBX_ZONE_INFOS_H

#include <ace_time/internal/ZoneInfo.h>

namespace ace_time {
namespace zonedbx {

//---------------------------------------------------------------------------
// ZoneContext (should not be in PROGMEM)
//---------------------------------------------------------------------------

// Version of the TZ Database which generated these files.
extern const char kTzDatabaseVersion[];

// Metadata about the zonedb files.
extern const extended::ZoneContext kZoneContext;

//---------------------------------------------------------------------------
// Supported zones: 387
//---------------------------------------------------------------------------

extern const extended::ZoneInfo kZoneAfrica_Abidjan; // Africa/Abidjan
extern const extended::ZoneInfo kZoneAfrica_Accra; // Africa/Accra
extern const extended::ZoneInfo kZoneAfrica_Algiers; // Africa/Algiers
extern const extended::ZoneInfo kZoneAfrica_Bissau; // Africa/Bissau
extern const extended::ZoneInfo kZoneAfrica_Cairo; // Africa/Cairo
extern const extended::ZoneInfo kZoneAfrica_Casablanca; // Africa/Casablanca
extern const extended::ZoneInfo kZoneAfrica_Ceuta; // Africa/Ceuta
extern const extended::ZoneInfo kZoneAfrica_El_Aaiun; // Africa/El_Aaiun
extern const extended::ZoneInfo kZoneAfrica_Johannesburg; // Africa/Johannesburg
extern const extended::ZoneInfo kZoneAfrica_Juba; // Africa/Juba
extern const extended::ZoneInfo kZoneAfrica_Khartoum; // Africa/Khartoum
extern const extended::ZoneInfo kZoneAfrica_Lagos; // Africa/Lagos
extern const extended::ZoneInfo kZoneAfrica_Maputo; // Africa/Maputo
extern const extended::ZoneInfo kZoneAfrica_Monrovia; // Africa/Monrovia
extern const extended::ZoneInfo kZoneAfrica_Nairobi; // Africa/Nairobi
extern const extended::ZoneInfo kZoneAfrica_Ndjamena; // Africa/Ndjamena
extern const extended::ZoneInfo kZoneAfrica_Sao_Tome; // Africa/Sao_Tome
extern const extended::ZoneInfo kZoneAfrica_Tripoli; // Africa/Tripoli
extern const extended::ZoneInfo kZoneAfrica_Tunis; // Africa/Tunis
extern const extended::ZoneInfo kZoneAfrica_Windhoek; // Africa/Windhoek
extern const extended::ZoneInfo kZoneAmerica_Adak; // America/Adak
extern const extended::ZoneInfo kZoneAmerica_Anchorage; // America/Anchorage
extern const extended::ZoneInfo kZoneAmerica_Araguaina; // America/Araguaina
extern const extended::ZoneInfo kZoneAmerica_Argentina_Buenos_Aires; // America/Argentina/Buenos_Aires
extern const extended::ZoneInfo kZoneAmerica_Argentina_Catamarca; // America/Argentina/Catamarca
extern const extended::ZoneInfo kZoneAmerica_Argentina_Cordoba; // America/Argentina/Cordoba
extern const extended::ZoneInfo kZoneAmerica_Argentina_Jujuy; // America/Argentina/Jujuy
extern const extended::ZoneInfo kZoneAmerica_Argentina_La_Rioja; // America/Argentina/La_Rioja
extern const extended::ZoneInfo kZoneAmerica_Argentina_Mendoza; // America/Argentina/Mendoza
extern const extended::ZoneInfo kZoneAmerica_Argentina_Rio_Gallegos; // America/Argentina/Rio_Gallegos
extern const extended::ZoneInfo kZoneAmerica_Argentina_Salta; // America/Argentina/Salta
extern const extended::ZoneInfo kZoneAmerica_Argentina_San_Juan; // America/Argentina/San_Juan
extern const extended::ZoneInfo kZoneAmerica_Argentina_San_Luis; // America/Argentina/San_Luis
extern const extended::ZoneInfo kZoneAmerica_Argentina_Tucuman; // America/Argentina/Tucuman
extern const extended::ZoneInfo kZoneAmerica_Argentina_Ushuaia; // America/Argentina/Ushuaia
extern const extended::ZoneInfo kZoneAmerica_Asuncion; // America/Asuncion
extern const extended::ZoneInfo kZoneAmerica_Atikokan; // America/Atikokan
extern const extended::ZoneInfo kZoneAmerica_Bahia; // America/Bahia
extern const extended::ZoneInfo kZoneAmerica_Bahia_Banderas; // America/Bahia_Banderas
extern const extended::ZoneInfo kZoneAmerica_Barbados; // America/Barbados
extern const extended::ZoneInfo kZoneAmerica_Belem; // America/Belem
extern const extended::ZoneInfo kZoneAmerica_Belize; // America/Belize
extern const extended::ZoneInfo kZoneAmerica_Blanc_Sablon; // America/Blanc-Sablon
extern const extended::ZoneInfo kZoneAmerica_Boa_Vista; // America/Boa_Vista
extern const extended::ZoneInfo kZoneAmerica_Bogota; // America/Bogota
extern const extended::ZoneInfo kZoneAmerica_Boise; // America/Boise
extern const extended::ZoneInfo kZoneAmerica_Cambridge_Bay; // America/Cambridge_Bay
extern const extended::ZoneInfo kZoneAmerica_Campo_Grande; // America/Campo_Grande
extern const extended::ZoneInfo kZoneAmerica_Cancun; // America/Cancun
extern const extended::ZoneInfo kZoneAmerica_Caracas; // America/Caracas
extern const extended::ZoneInfo kZoneAmerica_Cayenne; // America/Cayenne
extern const extended::ZoneInfo kZoneAmerica_Chicago; // America/Chicago
extern const extended::ZoneInfo kZoneAmerica_Chihuahua; // America/Chihuahua
extern const extended::ZoneInfo kZoneAmerica_Costa_Rica; // America/Costa_Rica
extern const extended::ZoneInfo kZoneAmerica_Creston; // America/Creston
extern const extended::ZoneInfo kZoneAmerica_Cuiaba; // America/Cuiaba
extern const extended::ZoneInfo kZoneAmerica_Curacao; // America/Curacao
extern const extended::ZoneInfo kZoneAmerica_Danmarkshavn; // America/Danmarkshavn
extern const extended::ZoneInfo kZoneAmerica_Dawson; // America/Dawson
extern const extended::ZoneInfo kZoneAmerica_Dawson_Creek; // America/Dawson_Creek
extern const extended::ZoneInfo kZoneAmerica_Denver; // America/Denver
extern const extended::ZoneInfo kZoneAmerica_Detroit; // America/Detroit
extern const extended::ZoneInfo kZoneAmerica_Edmonton; // America/Edmonton
extern const extended::ZoneInfo kZoneAmerica_Eirunepe; // America/Eirunepe
extern const extended::ZoneInfo kZoneAmerica_El_Salvador; // America/El_Salvador
extern const extended::ZoneInfo kZoneAmerica_Fort_Nelson; // America/Fort_Nelson
extern const extended::ZoneInfo kZoneAmerica_Fortaleza; // America/Fortaleza
extern const extended::ZoneInfo kZoneAmerica_Glace_Bay; // America/Glace_Bay
extern const extended::ZoneInfo kZoneAmerica_Godthab; // America/Godthab
extern const extended::ZoneInfo kZoneAmerica_Goose_Bay; // America/Goose_Bay
extern const extended::ZoneInfo kZoneAmerica_Grand_Turk; // America/Grand_Turk
extern const extended::ZoneInfo kZoneAmerica_Guatemala; // America/Guatemala
extern const extended::ZoneInfo kZoneAmerica_Guayaquil; // America/Guayaquil
extern const extended::ZoneInfo kZoneAmerica_Guyana; // America/Guyana
extern const extended::ZoneInfo kZoneAmerica_Halifax; // America/Halifax
extern const extended::ZoneInfo kZoneAmerica_Havana; // America/Havana
extern const extended::ZoneInfo kZoneAmerica_Hermosillo; // America/Hermosillo
extern const extended::ZoneInfo kZoneAmerica_Indiana_Indianapolis; // America/Indiana/Indianapolis
extern const extended::ZoneInfo kZoneAmerica_Indiana_Knox; // America/Indiana/Knox
extern const extended::ZoneInfo kZoneAmerica_Indiana_Marengo; // America/Indiana/Marengo
extern const extended::ZoneInfo kZoneAmerica_Indiana_Petersburg; // America/Indiana/Petersburg
extern const extended::ZoneInfo kZoneAmerica_Indiana_Tell_City; // America/Indiana/Tell_City
extern const extended::ZoneInfo kZoneAmerica_Indiana_Vevay; // America/Indiana/Vevay
extern const extended::ZoneInfo kZoneAmerica_Indiana_Vincennes; // America/Indiana/Vincennes
extern const extended::ZoneInfo kZoneAmerica_Indiana_Winamac; // America/Indiana/Winamac
extern const extended::ZoneInfo kZoneAmerica_Inuvik; // America/Inuvik
extern const extended::ZoneInfo kZoneAmerica_Iqaluit; // America/Iqaluit
extern const extended::ZoneInfo kZoneAmerica_Jamaica; // America/Jamaica
extern const extended::ZoneInfo kZoneAmerica_Juneau; // America/Juneau
extern const extended::ZoneInfo kZoneAmerica_Kentucky_Louisville; // America/Kentucky/Louisville
extern const extended::ZoneInfo kZoneAmerica_Kentucky_Monticello; // America/Kentucky/Monticello
extern const extended::ZoneInfo kZoneAmerica_La_Paz; // America/La_Paz
extern const extended::ZoneInfo kZoneAmerica_Lima; // America/Lima
extern const extended::ZoneInfo kZoneAmerica_Los_Angeles; // America/Los_Angeles
extern const extended::ZoneInfo kZoneAmerica_Maceio; // America/Maceio
extern const extended::ZoneInfo kZoneAmerica_Managua; // America/Managua
extern const extended::ZoneInfo kZoneAmerica_Manaus; // America/Manaus
extern const extended::ZoneInfo kZoneAmerica_Martinique; // America/Martinique
extern const extended::ZoneInfo kZoneAmerica_Matamoros; // America/Matamoros
extern const extended::ZoneInfo kZoneAmerica_Mazatlan; // America/Mazatlan
extern const extended::ZoneInfo kZoneAmerica_Menominee; // America/Menominee
extern const extended::ZoneInfo kZoneAmerica_Merida; // America/Merida
extern const extended::ZoneInfo kZoneAmerica_Metlakatla; // America/Metlakatla
extern const extended::ZoneInfo kZoneAmerica_Mexico_City; // America/Mexico_City
extern const extended::ZoneInfo kZoneAmerica_Miquelon; // America/Miquelon
extern const extended::ZoneInfo kZoneAmerica_Moncton; // America/Moncton
extern const extended::ZoneInfo kZoneAmerica_Monterrey; // America/Monterrey
extern const extended::ZoneInfo kZoneAmerica_Montevideo; // America/Montevideo
extern const extended::ZoneInfo kZoneAmerica_Nassau; // America/Nassau
extern const extended::ZoneInfo kZoneAmerica_New_York; // America/New_York
extern const extended::ZoneInfo kZoneAmerica_Nipigon; // America/Nipigon
extern const extended::ZoneInfo kZoneAmerica_Nome; // America/Nome
extern const extended::ZoneInfo kZoneAmerica_Noronha; // America/Noronha
extern const extended::ZoneInfo kZoneAmerica_North_Dakota_Beulah; // America/North_Dakota/Beulah
extern const extended::ZoneInfo kZoneAmerica_North_Dakota_Center; // America/North_Dakota/Center
extern const extended::ZoneInfo kZoneAmerica_North_Dakota_New_Salem; // America/North_Dakota/New_Salem
extern const extended::ZoneInfo kZoneAmerica_Ojinaga; // America/Ojinaga
extern const extended::ZoneInfo kZoneAmerica_Panama; // America/Panama
extern const extended::ZoneInfo kZoneAmerica_Pangnirtung; // America/Pangnirtung
extern const extended::ZoneInfo kZoneAmerica_Paramaribo; // America/Paramaribo
extern const extended::ZoneInfo kZoneAmerica_Phoenix; // America/Phoenix
extern const extended::ZoneInfo kZoneAmerica_Port_au_Prince; // America/Port-au-Prince
extern const extended::ZoneInfo kZoneAmerica_Port_of_Spain; // America/Port_of_Spain
extern const extended::ZoneInfo kZoneAmerica_Porto_Velho; // America/Porto_Velho
extern const extended::ZoneInfo kZoneAmerica_Puerto_Rico; // America/Puerto_Rico
extern const extended::ZoneInfo kZoneAmerica_Punta_Arenas; // America/Punta_Arenas
extern const extended::ZoneInfo kZoneAmerica_Rainy_River; // America/Rainy_River
extern const extended::ZoneInfo kZoneAmerica_Rankin_Inlet; // America/Rankin_Inlet
extern const extended::ZoneInfo kZoneAmerica_Recife; // America/Recife
extern const extended::ZoneInfo kZoneAmerica_Regina; // America/Regina
extern const extended::ZoneInfo kZoneAmerica_Resolute; // America/Resolute
extern const extended::ZoneInfo kZoneAmerica_Rio_Branco; // America/Rio_Branco
extern const extended::ZoneInfo kZoneAmerica_Santarem; // America/Santarem
extern const extended::ZoneInfo kZoneAmerica_Santiago; // America/Santiago
extern const extended::ZoneInfo kZoneAmerica_Santo_Domingo; // America/Santo_Domingo
extern const extended::ZoneInfo kZoneAmerica_Sao_Paulo; // America/Sao_Paulo
extern const extended::ZoneInfo kZoneAmerica_Scoresbysund; // America/Scoresbysund
extern const extended::ZoneInfo kZoneAmerica_Sitka; // America/Sitka
extern const extended::ZoneInfo kZoneAmerica_St_Johns; // America/St_Johns
extern const extended::ZoneInfo kZoneAmerica_Swift_Current; // America/Swift_Current
extern const extended::ZoneInfo kZoneAmerica_Tegucigalpa; // America/Tegucigalpa
extern const extended::ZoneInfo kZoneAmerica_Thule; // America/Thule
extern const extended::ZoneInfo kZoneAmerica_Thunder_Bay; // America/Thunder_Bay
extern const extended::ZoneInfo kZoneAmerica_Tijuana; // America/Tijuana
extern const extended::ZoneInfo kZoneAmerica_Toronto; // America/Toronto
extern const extended::ZoneInfo kZoneAmerica_Vancouver; // America/Vancouver
extern const extended::ZoneInfo kZoneAmerica_Whitehorse; // America/Whitehorse
extern const extended::ZoneInfo kZoneAmerica_Winnipeg; // America/Winnipeg
extern const extended::ZoneInfo kZoneAmerica_Yakutat; // America/Yakutat
extern const extended::ZoneInfo kZoneAmerica_Yellowknife; // America/Yellowknife
extern const extended::ZoneInfo kZoneAntarctica_Casey; // Antarctica/Casey
extern const extended::ZoneInfo kZoneAntarctica_Davis; // Antarctica/Davis
extern const extended::ZoneInfo kZoneAntarctica_DumontDUrville; // Antarctica/DumontDUrville
extern const extended::ZoneInfo kZoneAntarctica_Macquarie; // Antarctica/Macquarie
extern const extended::ZoneInfo kZoneAntarctica_Mawson; // Antarctica/Mawson
extern const extended::ZoneInfo kZoneAntarctica_Palmer; // Antarctica/Palmer
extern const extended::ZoneInfo kZoneAntarctica_Rothera; // Antarctica/Rothera
extern const extended::ZoneInfo kZoneAntarctica_Syowa; // Antarctica/Syowa
extern const extended::ZoneInfo kZoneAntarctica_Troll; // Antarctica/Troll
extern const extended::ZoneInfo kZoneAntarctica_Vostok; // Antarctica/Vostok
extern const extended::ZoneInfo kZoneAsia_Almaty; // Asia/Almaty
extern const extended::ZoneInfo kZoneAsia_Amman; // Asia/Amman
extern const extended::ZoneInfo kZoneAsia_Anadyr; // Asia/Anadyr
extern const extended::ZoneInfo kZoneAsia_Aqtau; // Asia/Aqtau
extern const extended::ZoneInfo kZoneAsia_Aqtobe; // Asia/Aqtobe
extern const extended::ZoneInfo kZoneAsia_Ashgabat; // Asia/Ashgabat
extern const extended::ZoneInfo kZoneAsia_Atyrau; // Asia/Atyrau
extern const extended::ZoneInfo kZoneAsia_Baghdad; // Asia/Baghdad
extern const extended::ZoneInfo kZoneAsia_Baku; // Asia/Baku
extern const extended::ZoneInfo kZoneAsia_Bangkok; // Asia/Bangkok
extern const extended::ZoneInfo kZoneAsia_Barnaul; // Asia/Barnaul
extern const extended::ZoneInfo kZoneAsia_Beirut; // Asia/Beirut
extern const extended::ZoneInfo kZoneAsia_Bishkek; // Asia/Bishkek
extern const extended::ZoneInfo kZoneAsia_Brunei; // Asia/Brunei
extern const extended::ZoneInfo kZoneAsia_Chita; // Asia/Chita
extern const extended::ZoneInfo kZoneAsia_Choibalsan; // Asia/Choibalsan
extern const extended::ZoneInfo kZoneAsia_Colombo; // Asia/Colombo
extern const extended::ZoneInfo kZoneAsia_Damascus; // Asia/Damascus
extern const extended::ZoneInfo kZoneAsia_Dhaka; // Asia/Dhaka
extern const extended::ZoneInfo kZoneAsia_Dili; // Asia/Dili
extern const extended::ZoneInfo kZoneAsia_Dubai; // Asia/Dubai
extern const extended::ZoneInfo kZoneAsia_Dushanbe; // Asia/Dushanbe
extern const extended::ZoneInfo kZoneAsia_Famagusta; // Asia/Famagusta
extern const extended::ZoneInfo kZoneAsia_Gaza; // Asia/Gaza
extern const extended::ZoneInfo kZoneAsia_Hebron; // Asia/Hebron
extern const extended::ZoneInfo kZoneAsia_Ho_Chi_Minh; // Asia/Ho_Chi_Minh
extern const extended::ZoneInfo kZoneAsia_Hong_Kong; // Asia/Hong_Kong
extern const extended::ZoneInfo kZoneAsia_Hovd; // Asia/Hovd
extern const extended::ZoneInfo kZoneAsia_Irkutsk; // Asia/Irkutsk
extern const extended::ZoneInfo kZoneAsia_Jakarta; // Asia/Jakarta
extern const extended::ZoneInfo kZoneAsia_Jayapura; // Asia/Jayapura
extern const extended::ZoneInfo kZoneAsia_Jerusalem; // Asia/Jerusalem
extern const extended::ZoneInfo kZoneAsia_Kabul; // Asia/Kabul
extern const extended::ZoneInfo kZoneAsia_Kamchatka; // Asia/Kamchatka
extern const extended::ZoneInfo kZoneAsia_Karachi; // Asia/Karachi
extern const extended::ZoneInfo kZoneAsia_Kathmandu; // Asia/Kathmandu
extern const extended::ZoneInfo kZoneAsia_Khandyga; // Asia/Khandyga
extern const extended::ZoneInfo kZoneAsia_Kolkata; // Asia/Kolkata
extern const extended::ZoneInfo kZoneAsia_Krasnoyarsk; // Asia/Krasnoyarsk
extern const extended::ZoneInfo kZoneAsia_Kuala_Lumpur; // Asia/Kuala_Lumpur
extern const extended::ZoneInfo kZoneAsia_Kuching; // Asia/Kuching
extern const extended::ZoneInfo kZoneAsia_Macau; // Asia/Macau
extern const extended::ZoneInfo kZoneAsia_Magadan; // Asia/Magadan
extern const extended::ZoneInfo kZoneAsia_Makassar; // Asia/Makassar
extern const extended::ZoneInfo kZoneAsia_Manila; // Asia/Manila
extern const extended::ZoneInfo kZoneAsia_Nicosia; // Asia/Nicosia
extern const extended::ZoneInfo kZoneAsia_Novokuznetsk; // Asia/Novokuznetsk
extern const extended::ZoneInfo kZoneAsia_Novosibirsk; // Asia/Novosibirsk
extern const extended::ZoneInfo kZoneAsia_Omsk; // Asia/Omsk
extern const extended::ZoneInfo kZoneAsia_Oral; // Asia/Oral
extern const extended::ZoneInfo kZoneAsia_Pontianak; // Asia/Pontianak
extern const extended::ZoneInfo kZoneAsia_Pyongyang; // Asia/Pyongyang
extern const extended::ZoneInfo kZoneAsia_Qatar; // Asia/Qatar
extern const extended::ZoneInfo kZoneAsia_Qostanay; // Asia/Qostanay
extern const extended::ZoneInfo kZoneAsia_Qyzylorda; // Asia/Qyzylorda
extern const extended::ZoneInfo kZoneAsia_Riyadh; // Asia/Riyadh
extern const extended::ZoneInfo kZoneAsia_Sakhalin; // Asia/Sakhalin
extern const extended::ZoneInfo kZoneAsia_Samarkand; // Asia/Samarkand
extern const extended::ZoneInfo kZoneAsia_Seoul; // Asia/Seoul
extern const extended::ZoneInfo kZoneAsia_Shanghai; // Asia/Shanghai
extern const extended::ZoneInfo kZoneAsia_Singapore; // Asia/Singapore
extern const extended::ZoneInfo kZoneAsia_Srednekolymsk; // Asia/Srednekolymsk
extern const extended::ZoneInfo kZoneAsia_Taipei; // Asia/Taipei
extern const extended::ZoneInfo kZoneAsia_Tashkent; // Asia/Tashkent
extern const extended::ZoneInfo kZoneAsia_Tbilisi; // Asia/Tbilisi
extern const extended::ZoneInfo kZoneAsia_Tehran; // Asia/Tehran
extern const extended::ZoneInfo kZoneAsia_Thimphu; // Asia/Thimphu
extern const extended::ZoneInfo kZoneAsia_Tokyo; // Asia/Tokyo
extern const extended::ZoneInfo kZoneAsia_Tomsk; // Asia/Tomsk
extern const extended::ZoneInfo kZoneAsia_Ulaanbaatar; // Asia/Ulaanbaatar
extern const extended::ZoneInfo kZoneAsia_Urumqi; // Asia/Urumqi
extern const extended::ZoneInfo kZoneAsia_Ust_Nera; // Asia/Ust-Nera
extern const extended::ZoneInfo kZoneAsia_Vladivostok; // Asia/Vladivostok
extern const extended::ZoneInfo kZoneAsia_Yakutsk; // Asia/Yakutsk
extern const extended::ZoneInfo kZoneAsia_Yangon; // Asia/Yangon
extern const extended::ZoneInfo kZoneAsia_Yekaterinburg; // Asia/Yekaterinburg
extern const extended::ZoneInfo kZoneAsia_Yerevan; // Asia/Yerevan
extern const extended::ZoneInfo kZoneAtlantic_Azores; // Atlantic/Azores
extern const extended::ZoneInfo kZoneAtlantic_Bermuda; // Atlantic/Bermuda
extern const extended::ZoneInfo kZoneAtlantic_Canary; // Atlantic/Canary
extern const extended::ZoneInfo kZoneAtlantic_Cape_Verde; // Atlantic/Cape_Verde
extern const extended::ZoneInfo kZoneAtlantic_Faroe; // Atlantic/Faroe
extern const extended::ZoneInfo kZoneAtlantic_Madeira; // Atlantic/Madeira
extern const extended::ZoneInfo kZoneAtlantic_Reykjavik; // Atlantic/Reykjavik
extern const extended::ZoneInfo kZoneAtlantic_South_Georgia; // Atlantic/South_Georgia
extern const extended::ZoneInfo kZoneAtlantic_Stanley; // Atlantic/Stanley
extern const extended::ZoneInfo kZoneAustralia_Adelaide; // Australia/Adelaide
extern const extended::ZoneInfo kZoneAustralia_Brisbane; // Australia/Brisbane
extern const extended::ZoneInfo kZoneAustralia_Broken_Hill; // Australia/Broken_Hill
extern const extended::ZoneInfo kZoneAustralia_Currie; // Australia/Currie
extern const extended::ZoneInfo kZoneAustralia_Darwin; // Australia/Darwin
extern const extended::ZoneInfo kZoneAustralia_Eucla; // Australia/Eucla
extern const extended::ZoneInfo kZoneAustralia_Hobart; // Australia/Hobart
extern const extended::ZoneInfo kZoneAustralia_Lindeman; // Australia/Lindeman
extern const extended::ZoneInfo kZoneAustralia_Lord_Howe; // Australia/Lord_Howe
extern const extended::ZoneInfo kZoneAustralia_Melbourne; // Australia/Melbourne
extern const extended::ZoneInfo kZoneAustralia_Perth; // Australia/Perth
extern const extended::ZoneInfo kZoneAustralia_Sydney; // Australia/Sydney
extern const extended::ZoneInfo kZoneCET; // CET
extern const extended::ZoneInfo kZoneCST6CDT; // CST6CDT
extern const extended::ZoneInfo kZoneEET; // EET
extern const extended::ZoneInfo kZoneEST; // EST
extern const extended::ZoneInfo kZoneEST5EDT; // EST5EDT
extern const extended::ZoneInfo kZoneEtc_GMT; // Etc/GMT
extern const extended::ZoneInfo kZoneEtc_GMT_PLUS_1; // Etc/GMT+1
extern const extended::ZoneInfo kZoneEtc_GMT_PLUS_10; // Etc/GMT+10
extern const extended::ZoneInfo kZoneEtc_GMT_PLUS_11; // Etc/GMT+11
extern const extended::ZoneInfo kZoneEtc_GMT_PLUS_12; // Etc/GMT+12
extern const extended::ZoneInfo kZoneEtc_GMT_PLUS_2; // Etc/GMT+2
extern const extended::ZoneInfo kZoneEtc_GMT_PLUS_3; // Etc/GMT+3
extern const extended::ZoneInfo kZoneEtc_GMT_PLUS_4; // Etc/GMT+4
extern const extended::ZoneInfo kZoneEtc_GMT_PLUS_5; // Etc/GMT+5
extern const extended::ZoneInfo kZoneEtc_GMT_PLUS_6; // Etc/GMT+6
extern const extended::ZoneInfo kZoneEtc_GMT_PLUS_7; // Etc/GMT+7
extern const extended::ZoneInfo kZoneEtc_GMT_PLUS_8; // Etc/GMT+8
extern const extended::ZoneInfo kZoneEtc_GMT_PLUS_9; // Etc/GMT+9
extern const extended::ZoneInfo kZoneEtc_GMT_1; // Etc/GMT-1
extern const extended::ZoneInfo kZoneEtc_GMT_10; // Etc/GMT-10
extern const extended::ZoneInfo kZoneEtc_GMT_11; // Etc/GMT-11
extern const extended::ZoneInfo kZoneEtc_GMT_12; // Etc/GMT-12
extern const extended::ZoneInfo kZoneEtc_GMT_13; // Etc/GMT-13
extern const extended::ZoneInfo kZoneEtc_GMT_14; // Etc/GMT-14
extern const extended::ZoneInfo kZoneEtc_GMT_2; // Etc/GMT-2
extern const extended::ZoneInfo kZoneEtc_GMT_3; // Etc/GMT-3
extern const extended::ZoneInfo kZoneEtc_GMT_4; // Etc/GMT-4
extern const extended::ZoneInfo kZoneEtc_GMT_5; // Etc/GMT-5
extern const extended::ZoneInfo kZoneEtc_GMT_6; // Etc/GMT-6
extern const extended::ZoneInfo kZoneEtc_GMT_7; // Etc/GMT-7
extern const extended::ZoneInfo kZoneEtc_GMT_8; // Etc/GMT-8
extern const extended::ZoneInfo kZoneEtc_GMT_9; // Etc/GMT-9
extern const extended::ZoneInfo kZoneEtc_UTC; // Etc/UTC
extern const extended::ZoneInfo kZoneEurope_Amsterdam; // Europe/Amsterdam
extern const extended::ZoneInfo kZoneEurope_Andorra; // Europe/Andorra
extern const extended::ZoneInfo kZoneEurope_Astrakhan; // Europe/Astrakhan
extern const extended::ZoneInfo kZoneEurope_Athens; // Europe/Athens
extern const extended::ZoneInfo kZoneEurope_Belgrade; // Europe/Belgrade
extern const extended::ZoneInfo kZoneEurope_Berlin; // Europe/Berlin
extern const extended::ZoneInfo kZoneEurope_Brussels; // Europe/Brussels
extern const extended::ZoneInfo kZoneEurope_Bucharest; // Europe/Bucharest
extern const extended::ZoneInfo kZoneEurope_Budapest; // Europe/Budapest
extern const extended::ZoneInfo kZoneEurope_Chisinau; // Europe/Chisinau
extern const extended::ZoneInfo kZoneEurope_Copenhagen; // Europe/Copenhagen
extern const extended::ZoneInfo kZoneEurope_Dublin; // Europe/Dublin
extern const extended::ZoneInfo kZoneEurope_Gibraltar; // Europe/Gibraltar
extern const extended::ZoneInfo kZoneEurope_Helsinki; // Europe/Helsinki
extern const extended::ZoneInfo kZoneEurope_Istanbul; // Europe/Istanbul
extern const extended::ZoneInfo kZoneEurope_Kaliningrad; // Europe/Kaliningrad
extern const extended::ZoneInfo kZoneEurope_Kiev; // Europe/Kiev
extern const extended::ZoneInfo kZoneEurope_Kirov; // Europe/Kirov
extern const extended::ZoneInfo kZoneEurope_Lisbon; // Europe/Lisbon
extern const extended::ZoneInfo kZoneEurope_London; // Europe/London
extern const extended::ZoneInfo kZoneEurope_Luxembourg; // Europe/Luxembourg
extern const extended::ZoneInfo kZoneEurope_Madrid; // Europe/Madrid
extern const extended::ZoneInfo kZoneEurope_Malta; // Europe/Malta
extern const extended::ZoneInfo kZoneEurope_Minsk; // Europe/Minsk
extern const extended::ZoneInfo kZoneEurope_Monaco; // Europe/Monaco
extern const extended::ZoneInfo kZoneEurope_Moscow; // Europe/Moscow
extern const extended::ZoneInfo kZoneEurope_Oslo; // Europe/Oslo
extern const extended::ZoneInfo kZoneEurope_Paris; // Europe/Paris
extern const extended::ZoneInfo kZoneEurope_Prague; // Europe/Prague
extern const extended::ZoneInfo kZoneEurope_Riga; // Europe/Riga
extern const extended::ZoneInfo kZoneEurope_Rome; // Europe/Rome
extern const extended::ZoneInfo kZoneEurope_Samara; // Europe/Samara
extern const extended::ZoneInfo kZoneEurope_Saratov; // Europe/Saratov
extern const extended::ZoneInfo kZoneEurope_Simferopol; // Europe/Simferopol
extern const extended::ZoneInfo kZoneEurope_Sofia; // Europe/Sofia
extern const extended::ZoneInfo kZoneEurope_Stockholm; // Europe/Stockholm
extern const extended::ZoneInfo kZoneEurope_Tallinn; // Europe/Tallinn
extern const extended::ZoneInfo kZoneEurope_Tirane; // Europe/Tirane
extern const extended::ZoneInfo kZoneEurope_Ulyanovsk; // Europe/Ulyanovsk
extern const extended::ZoneInfo kZoneEurope_Uzhgorod; // Europe/Uzhgorod
extern const extended::ZoneInfo kZoneEurope_Vienna; // Europe/Vienna
extern const extended::ZoneInfo kZoneEurope_Vilnius; // Europe/Vilnius
extern const extended::ZoneInfo kZoneEurope_Volgograd; // Europe/Volgograd
extern const extended::ZoneInfo kZoneEurope_Warsaw; // Europe/Warsaw
extern const extended::ZoneInfo kZoneEurope_Zaporozhye; // Europe/Zaporozhye
extern const extended::ZoneInfo kZoneEurope_Zurich; // Europe/Zurich
extern const extended::ZoneInfo kZoneHST; // HST
extern const extended::ZoneInfo kZoneIndian_Chagos; // Indian/Chagos
extern const extended::ZoneInfo kZoneIndian_Christmas; // Indian/Christmas
extern const extended::ZoneInfo kZoneIndian_Cocos; // Indian/Cocos
extern const extended::ZoneInfo kZoneIndian_Kerguelen; // Indian/Kerguelen
extern const extended::ZoneInfo kZoneIndian_Mahe; // Indian/Mahe
extern const extended::ZoneInfo kZoneIndian_Maldives; // Indian/Maldives
extern const extended::ZoneInfo kZoneIndian_Mauritius; // Indian/Mauritius
extern const extended::ZoneInfo kZoneIndian_Reunion; // Indian/Reunion
extern const extended::ZoneInfo kZoneMET; // MET
extern const extended::ZoneInfo kZoneMST; // MST
extern const extended::ZoneInfo kZoneMST7MDT; // MST7MDT
extern const extended::ZoneInfo kZonePST8PDT; // PST8PDT
extern const extended::ZoneInfo kZonePacific_Apia; // Pacific/Apia
extern const extended::ZoneInfo kZonePacific_Auckland; // Pacific/Auckland
extern const extended::ZoneInfo kZonePacific_Bougainville; // Pacific/Bougainville
extern const extended::ZoneInfo kZonePacific_Chatham; // Pacific/Chatham
extern const extended::ZoneInfo kZonePacific_Chuuk; // Pacific/Chuuk
extern const extended::ZoneInfo kZonePacific_Easter; // Pacific/Easter
extern const extended::ZoneInfo kZonePacific_Efate; // Pacific/Efate
extern const extended::ZoneInfo kZonePacific_Enderbury; // Pacific/Enderbury
extern const extended::ZoneInfo kZonePacific_Fakaofo; // Pacific/Fakaofo
extern const extended::ZoneInfo kZonePacific_Fiji; // Pacific/Fiji
extern const extended::ZoneInfo kZonePacific_Funafuti; // Pacific/Funafuti
extern const extended::ZoneInfo kZonePacific_Galapagos; // Pacific/Galapagos
extern const extended::ZoneInfo kZonePacific_Gambier; // Pacific/Gambier
extern const extended::ZoneInfo kZonePacific_Guadalcanal; // Pacific/Guadalcanal
extern const extended::ZoneInfo kZonePacific_Guam; // Pacific/Guam
extern const extended::ZoneInfo kZonePacific_Honolulu; // Pacific/Honolulu
extern const extended::ZoneInfo kZonePacific_Kiritimati; // Pacific/Kiritimati
extern const extended::ZoneInfo kZonePacific_Kosrae; // Pacific/Kosrae
extern const extended::ZoneInfo kZonePacific_Kwajalein; // Pacific/Kwajalein
extern const extended::ZoneInfo kZonePacific_Majuro; // Pacific/Majuro
extern const extended::ZoneInfo kZonePacific_Marquesas; // Pacific/Marquesas
extern const extended::ZoneInfo kZonePacific_Nauru; // Pacific/Nauru
extern const extended::ZoneInfo kZonePacific_Niue; // Pacific/Niue
extern const extended::ZoneInfo kZonePacific_Norfolk; // Pacific/Norfolk
extern const extended::ZoneInfo kZonePacific_Noumea; // Pacific/Noumea
extern const extended::ZoneInfo kZonePacific_Pago_Pago; // Pacific/Pago_Pago
extern const extended::ZoneInfo kZonePacific_Palau; // Pacific/Palau
extern const extended::ZoneInfo kZonePacific_Pitcairn; // Pacific/Pitcairn
extern const extended::ZoneInfo kZonePacific_Pohnpei; // Pacific/Pohnpei
extern const extended::ZoneInfo kZonePacific_Port_Moresby; // Pacific/Port_Moresby
extern const extended::ZoneInfo kZonePacific_Rarotonga; // Pacific/Rarotonga
extern const extended::ZoneInfo kZonePacific_Tahiti; // Pacific/Tahiti
extern const extended::ZoneInfo kZonePacific_Tarawa; // Pacific/Tarawa
extern const extended::ZoneInfo kZonePacific_Tongatapu; // Pacific/Tongatapu
extern const extended::ZoneInfo kZonePacific_Wake; // Pacific/Wake
extern const extended::ZoneInfo kZonePacific_Wallis; // Pacific/Wallis
extern const extended::ZoneInfo kZoneWET; // WET


//---------------------------------------------------------------------------
// Supported links: 205
//---------------------------------------------------------------------------

extern const extended::ZoneInfo& kZoneAfrica_Addis_Ababa; // Africa/Addis_Ababa -> Africa/Nairobi
extern const extended::ZoneInfo& kZoneAfrica_Asmara; // Africa/Asmara -> Africa/Nairobi
extern const extended::ZoneInfo& kZoneAfrica_Asmera; // Africa/Asmera -> Africa/Nairobi
extern const extended::ZoneInfo& kZoneAfrica_Bamako; // Africa/Bamako -> Africa/Abidjan
extern const extended::ZoneInfo& kZoneAfrica_Bangui; // Africa/Bangui -> Africa/Lagos
extern const extended::ZoneInfo& kZoneAfrica_Banjul; // Africa/Banjul -> Africa/Abidjan
extern const extended::ZoneInfo& kZoneAfrica_Blantyre; // Africa/Blantyre -> Africa/Maputo
extern const extended::ZoneInfo& kZoneAfrica_Brazzaville; // Africa/Brazzaville -> Africa/Lagos
extern const extended::ZoneInfo& kZoneAfrica_Bujumbura; // Africa/Bujumbura -> Africa/Maputo
extern const extended::ZoneInfo& kZoneAfrica_Conakry; // Africa/Conakry -> Africa/Abidjan
extern const extended::ZoneInfo& kZoneAfrica_Dakar; // Africa/Dakar -> Africa/Abidjan
extern const extended::ZoneInfo& kZoneAfrica_Dar_es_Salaam; // Africa/Dar_es_Salaam -> Africa/Nairobi
extern const extended::ZoneInfo& kZoneAfrica_Djibouti; // Africa/Djibouti -> Africa/Nairobi
extern const extended::ZoneInfo& kZoneAfrica_Douala; // Africa/Douala -> Africa/Lagos
extern const extended::ZoneInfo& kZoneAfrica_Freetown; // Africa/Freetown -> Africa/Abidjan
extern const extended::ZoneInfo& kZoneAfrica_Gaborone; // Africa/Gaborone -> Africa/Maputo
extern const extended::ZoneInfo& kZoneAfrica_Harare; // Africa/Harare -> Africa/Maputo
extern const extended::ZoneInfo& kZoneAfrica_Kampala; // Africa/Kampala -> Africa/Nairobi
extern const extended::ZoneInfo& kZoneAfrica_Kigali; // Africa/Kigali -> Africa/Maputo
extern const extended::ZoneInfo& kZoneAfrica_Kinshasa; // Africa/Kinshasa -> Africa/Lagos
extern const extended::ZoneInfo& kZoneAfrica_Libreville; // Africa/Libreville -> Africa/Lagos
extern const extended::ZoneInfo& kZoneAfrica_Lome; // Africa/Lome -> Africa/Abidjan
extern const extended::ZoneInfo& kZoneAfrica_Luanda; // Africa/Luanda -> Africa/Lagos
extern const extended::ZoneInfo& kZoneAfrica_Lubumbashi; // Africa/Lubumbashi -> Africa/Maputo
extern const extended::ZoneInfo& kZoneAfrica_Lusaka; // Africa/Lusaka -> Africa/Maputo
extern const extended::ZoneInfo& kZoneAfrica_Malabo; // Africa/Malabo -> Africa/Lagos
extern const extended::ZoneInfo& kZoneAfrica_Maseru; // Africa/Maseru -> Africa/Johannesburg
extern const extended::ZoneInfo& kZoneAfrica_Mbabane; // Africa/Mbabane -> Africa/Johannesburg
extern const extended::ZoneInfo& kZoneAfrica_Mogadishu; // Africa/Mogadishu -> Africa/Nairobi
extern const extended::ZoneInfo& kZoneAfrica_Niamey; // Africa/Niamey -> Africa/Lagos
extern const extended::ZoneInfo& kZoneAfrica_Nouakchott; // Africa/Nouakchott -> Africa/Abidjan
extern const extended::ZoneInfo& kZoneAfrica_Ouagadougou; // Africa/Ouagadougou -> Africa/Abidjan
extern const extended::ZoneInfo& kZoneAfrica_Porto_Novo; // Africa/Porto-Novo -> Africa/Lagos
extern const extended::ZoneInfo& kZoneAfrica_Timbuktu; // Africa/Timbuktu -> Africa/Abidjan
extern const extended::ZoneInfo& kZoneAmerica_Anguilla; // America/Anguilla -> America/Port_of_Spain
extern const extended::ZoneInfo& kZoneAmerica_Antigua; // America/Antigua -> America/Port_of_Spain
extern const extended::ZoneInfo& kZoneAmerica_Argentina_ComodRivadavia; // America/Argentina/ComodRivadavia -> America/Argentina/Catamarca
extern const extended::ZoneInfo& kZoneAmerica_Aruba; // America/Aruba -> America/Curacao
extern const extended::ZoneInfo& kZoneAmerica_Atka; // America/Atka -> America/Adak
extern const extended::ZoneInfo& kZoneAmerica_Buenos_Aires; // America/Buenos_Aires -> America/Argentina/Buenos_Aires
extern const extended::ZoneInfo& kZoneAmerica_Catamarca; // America/Catamarca -> America/Argentina/Catamarca
extern const extended::ZoneInfo& kZoneAmerica_Cayman; // America/Cayman -> America/Panama
extern const extended::ZoneInfo& kZoneAmerica_Coral_Harbour; // America/Coral_Harbour -> America/Atikokan
extern const extended::ZoneInfo& kZoneAmerica_Cordoba; // America/Cordoba -> America/Argentina/Cordoba
extern const extended::ZoneInfo& kZoneAmerica_Dominica; // America/Dominica -> America/Port_of_Spain
extern const extended::ZoneInfo& kZoneAmerica_Ensenada; // America/Ensenada -> America/Tijuana
extern const extended::ZoneInfo& kZoneAmerica_Fort_Wayne; // America/Fort_Wayne -> America/Indiana/Indianapolis
extern const extended::ZoneInfo& kZoneAmerica_Grenada; // America/Grenada -> America/Port_of_Spain
extern const extended::ZoneInfo& kZoneAmerica_Guadeloupe; // America/Guadeloupe -> America/Port_of_Spain
extern const extended::ZoneInfo& kZoneAmerica_Indianapolis; // America/Indianapolis -> America/Indiana/Indianapolis
extern const extended::ZoneInfo& kZoneAmerica_Jujuy; // America/Jujuy -> America/Argentina/Jujuy
extern const extended::ZoneInfo& kZoneAmerica_Knox_IN; // America/Knox_IN -> America/Indiana/Knox
extern const extended::ZoneInfo& kZoneAmerica_Kralendijk; // America/Kralendijk -> America/Curacao
extern const extended::ZoneInfo& kZoneAmerica_Louisville; // America/Louisville -> America/Kentucky/Louisville
extern const extended::ZoneInfo& kZoneAmerica_Lower_Princes; // America/Lower_Princes -> America/Curacao
extern const extended::ZoneInfo& kZoneAmerica_Marigot; // America/Marigot -> America/Port_of_Spain
extern const extended::ZoneInfo& kZoneAmerica_Mendoza; // America/Mendoza -> America/Argentina/Mendoza
extern const extended::ZoneInfo& kZoneAmerica_Montreal; // America/Montreal -> America/Toronto
extern const extended::ZoneInfo& kZoneAmerica_Montserrat; // America/Montserrat -> America/Port_of_Spain
extern const extended::ZoneInfo& kZoneAmerica_Porto_Acre; // America/Porto_Acre -> America/Rio_Branco
extern const extended::ZoneInfo& kZoneAmerica_Rosario; // America/Rosario -> America/Argentina/Cordoba
extern const extended::ZoneInfo& kZoneAmerica_Santa_Isabel; // America/Santa_Isabel -> America/Tijuana
extern const extended::ZoneInfo& kZoneAmerica_Shiprock; // America/Shiprock -> America/Denver
extern const extended::ZoneInfo& kZoneAmerica_St_Barthelemy; // America/St_Barthelemy -> America/Port_of_Spain
extern const extended::ZoneInfo& kZoneAmerica_St_Kitts; // America/St_Kitts -> America/Port_of_Spain
extern const extended::ZoneInfo& kZoneAmerica_St_Lucia; // America/St_Lucia -> America/Port_of_Spain
extern const extended::ZoneInfo& kZoneAmerica_St_Thomas; // America/St_Thomas -> America/Port_of_Spain
extern const extended::ZoneInfo& kZoneAmerica_St_Vincent; // America/St_Vincent -> America/Port_of_Spain
extern const extended::ZoneInfo& kZoneAmerica_Tortola; // America/Tortola -> America/Port_of_Spain
extern const extended::ZoneInfo& kZoneAmerica_Virgin; // America/Virgin -> America/Port_of_Spain
extern const extended::ZoneInfo& kZoneAntarctica_McMurdo; // Antarctica/McMurdo -> Pacific/Auckland
extern const extended::ZoneInfo& kZoneAntarctica_South_Pole; // Antarctica/South_Pole -> Pacific/Auckland
extern const extended::ZoneInfo& kZoneArctic_Longyearbyen; // Arctic/Longyearbyen -> Europe/Oslo
extern const extended::ZoneInfo& kZoneAsia_Aden; // Asia/Aden -> Asia/Riyadh
extern const extended::ZoneInfo& kZoneAsia_Ashkhabad; // Asia/Ashkhabad -> Asia/Ashgabat
extern const extended::ZoneInfo& kZoneAsia_Bahrain; // Asia/Bahrain -> Asia/Qatar
extern const extended::ZoneInfo& kZoneAsia_Calcutta; // Asia/Calcutta -> Asia/Kolkata
extern const extended::ZoneInfo& kZoneAsia_Chongqing; // Asia/Chongqing -> Asia/Shanghai
extern const extended::ZoneInfo& kZoneAsia_Chungking; // Asia/Chungking -> Asia/Shanghai
extern const extended::ZoneInfo& kZoneAsia_Dacca; // Asia/Dacca -> Asia/Dhaka
extern const extended::ZoneInfo& kZoneAsia_Harbin; // Asia/Harbin -> Asia/Shanghai
extern const extended::ZoneInfo& kZoneAsia_Istanbul; // Asia/Istanbul -> Europe/Istanbul
extern const extended::ZoneInfo& kZoneAsia_Kashgar; // Asia/Kashgar -> Asia/Urumqi
extern const extended::ZoneInfo& kZoneAsia_Katmandu; // Asia/Katmandu -> Asia/Kathmandu
extern const extended::ZoneInfo& kZoneAsia_Kuwait; // Asia/Kuwait -> Asia/Riyadh
extern const extended::ZoneInfo& kZoneAsia_Macao; // Asia/Macao -> Asia/Macau
extern const extended::ZoneInfo& kZoneAsia_Muscat; // Asia/Muscat -> Asia/Dubai
extern const extended::ZoneInfo& kZoneAsia_Phnom_Penh; // Asia/Phnom_Penh -> Asia/Bangkok
extern const extended::ZoneInfo& kZoneAsia_Rangoon; // Asia/Rangoon -> Asia/Yangon
extern const extended::ZoneInfo& kZoneAsia_Saigon; // Asia/Saigon -> Asia/Ho_Chi_Minh
extern const extended::ZoneInfo& kZoneAsia_Tel_Aviv; // Asia/Tel_Aviv -> Asia/Jerusalem
extern const extended::ZoneInfo& kZoneAsia_Thimbu; // Asia/Thimbu -> Asia/Thimphu
extern const extended::ZoneInfo& kZoneAsia_Ujung_Pandang; // Asia/Ujung_Pandang -> Asia/Makassar
extern const extended::ZoneInfo& kZoneAsia_Ulan_Bator; // Asia/Ulan_Bator -> Asia/Ulaanbaatar
extern const extended::ZoneInfo& kZoneAsia_Vientiane; // Asia/Vientiane -> Asia/Bangkok
extern const extended::ZoneInfo& kZoneAtlantic_Faeroe; // Atlantic/Faeroe -> Atlantic/Faroe
extern const extended::ZoneInfo& kZoneAtlantic_Jan_Mayen; // Atlantic/Jan_Mayen -> Europe/Oslo
extern const extended::ZoneInfo& kZoneAtlantic_St_Helena; // Atlantic/St_Helena -> Africa/Abidjan
extern const extended::ZoneInfo& kZoneAustralia_ACT; // Australia/ACT -> Australia/Sydney
extern const extended::ZoneInfo& kZoneAustralia_Canberra; // Australia/Canberra -> Australia/Sydney
extern const extended::ZoneInfo& kZoneAustralia_LHI; // Australia/LHI -> Australia/Lord_Howe
extern const extended::ZoneInfo& kZoneAustralia_NSW; // Australia/NSW -> Australia/Sydney
extern const extended::ZoneInfo& kZoneAustralia_North; // Australia/North -> Australia/Darwin
extern const extended::ZoneInfo& kZoneAustralia_Queensland; // Australia/Queensland -> Australia/Brisbane
extern const extended::ZoneInfo& kZoneAustralia_South; // Australia/South -> Australia/Adelaide
extern const extended::ZoneInfo& kZoneAustralia_Tasmania; // Australia/Tasmania -> Australia/Hobart
extern const extended::ZoneInfo& kZoneAustralia_Victoria; // Australia/Victoria -> Australia/Melbourne
extern const extended::ZoneInfo& kZoneAustralia_West; // Australia/West -> Australia/Perth
extern const extended::ZoneInfo& kZoneAustralia_Yancowinna; // Australia/Yancowinna -> Australia/Broken_Hill
extern const extended::ZoneInfo& kZoneBrazil_Acre; // Brazil/Acre -> America/Rio_Branco
extern const extended::ZoneInfo& kZoneBrazil_DeNoronha; // Brazil/DeNoronha -> America/Noronha
extern const extended::ZoneInfo& kZoneBrazil_East; // Brazil/East -> America/Sao_Paulo
extern const extended::ZoneInfo& kZoneBrazil_West; // Brazil/West -> America/Manaus
extern const extended::ZoneInfo& kZoneCanada_Atlantic; // Canada/Atlantic -> America/Halifax
extern const extended::ZoneInfo& kZoneCanada_Central; // Canada/Central -> America/Winnipeg
extern const extended::ZoneInfo& kZoneCanada_Eastern; // Canada/Eastern -> America/Toronto
extern const extended::ZoneInfo& kZoneCanada_Mountain; // Canada/Mountain -> America/Edmonton
extern const extended::ZoneInfo& kZoneCanada_Newfoundland; // Canada/Newfoundland -> America/St_Johns
extern const extended::ZoneInfo& kZoneCanada_Pacific; // Canada/Pacific -> America/Vancouver
extern const extended::ZoneInfo& kZoneCanada_Saskatchewan; // Canada/Saskatchewan -> America/Regina
extern const extended::ZoneInfo& kZoneCanada_Yukon; // Canada/Yukon -> America/Whitehorse
extern const extended::ZoneInfo& kZoneChile_Continental; // Chile/Continental -> America/Santiago
extern const extended::ZoneInfo& kZoneChile_EasterIsland; // Chile/EasterIsland -> Pacific/Easter
extern const extended::ZoneInfo& kZoneCuba; // Cuba -> America/Havana
extern const extended::ZoneInfo& kZoneEgypt; // Egypt -> Africa/Cairo
extern const extended::ZoneInfo& kZoneEire; // Eire -> Europe/Dublin
extern const extended::ZoneInfo& kZoneEtc_GMT_PLUS_0; // Etc/GMT+0 -> Etc/GMT
extern const extended::ZoneInfo& kZoneEtc_GMT_0; // Etc/GMT-0 -> Etc/GMT
extern const extended::ZoneInfo& kZoneEtc_GMT0; // Etc/GMT0 -> Etc/GMT
extern const extended::ZoneInfo& kZoneEtc_Greenwich; // Etc/Greenwich -> Etc/GMT
extern const extended::ZoneInfo& kZoneEtc_UCT; // Etc/UCT -> Etc/UTC
extern const extended::ZoneInfo& kZoneEtc_Universal; // Etc/Universal -> Etc/UTC
extern const extended::ZoneInfo& kZoneEtc_Zulu; // Etc/Zulu -> Etc/UTC
extern const extended::ZoneInfo& kZoneEurope_Belfast; // Europe/Belfast -> Europe/London
extern const extended::ZoneInfo& kZoneEurope_Bratislava; // Europe/Bratislava -> Europe/Prague
extern const extended::ZoneInfo& kZoneEurope_Busingen; // Europe/Busingen -> Europe/Zurich
extern const extended::ZoneInfo& kZoneEurope_Guernsey; // Europe/Guernsey -> Europe/London
extern const extended::ZoneInfo& kZoneEurope_Isle_of_Man; // Europe/Isle_of_Man -> Europe/London
extern const extended::ZoneInfo& kZoneEurope_Jersey; // Europe/Jersey -> Europe/London
extern const extended::ZoneInfo& kZoneEurope_Ljubljana; // Europe/Ljubljana -> Europe/Belgrade
extern const extended::ZoneInfo& kZoneEurope_Mariehamn; // Europe/Mariehamn -> Europe/Helsinki
extern const extended::ZoneInfo& kZoneEurope_Nicosia; // Europe/Nicosia -> Asia/Nicosia
extern const extended::ZoneInfo& kZoneEurope_Podgorica; // Europe/Podgorica -> Europe/Belgrade
extern const extended::ZoneInfo& kZoneEurope_San_Marino; // Europe/San_Marino -> Europe/Rome
extern const extended::ZoneInfo& kZoneEurope_Sarajevo; // Europe/Sarajevo -> Europe/Belgrade
extern const extended::ZoneInfo& kZoneEurope_Skopje; // Europe/Skopje -> Europe/Belgrade
extern const extended::ZoneInfo& kZoneEurope_Tiraspol; // Europe/Tiraspol -> Europe/Chisinau
extern const extended::ZoneInfo& kZoneEurope_Vaduz; // Europe/Vaduz -> Europe/Zurich
extern const extended::ZoneInfo& kZoneEurope_Vatican; // Europe/Vatican -> Europe/Rome
extern const extended::ZoneInfo& kZoneEurope_Zagreb; // Europe/Zagreb -> Europe/Belgrade
extern const extended::ZoneInfo& kZoneGB; // GB -> Europe/London
extern const extended::ZoneInfo& kZoneGB_Eire; // GB-Eire -> Europe/London
extern const extended::ZoneInfo& kZoneGMT; // GMT -> Etc/GMT
extern const extended::ZoneInfo& kZoneGMT_PLUS_0; // GMT+0 -> Etc/GMT
extern const extended::ZoneInfo& kZoneGMT_0; // GMT-0 -> Etc/GMT
extern const extended::ZoneInfo& kZoneGMT0; // GMT0 -> Etc/GMT
extern const extended::ZoneInfo& kZoneGreenwich; // Greenwich -> Etc/GMT
extern const extended::ZoneInfo& kZoneHongkong; // Hongkong -> Asia/Hong_Kong
extern const extended::ZoneInfo& kZoneIceland; // Iceland -> Atlantic/Reykjavik
extern const extended::ZoneInfo& kZoneIndian_Antananarivo; // Indian/Antananarivo -> Africa/Nairobi
extern const extended::ZoneInfo& kZoneIndian_Comoro; // Indian/Comoro -> Africa/Nairobi
extern const extended::ZoneInfo& kZoneIndian_Mayotte; // Indian/Mayotte -> Africa/Nairobi
extern const extended::ZoneInfo& kZoneIran; // Iran -> Asia/Tehran
extern const extended::ZoneInfo& kZoneIsrael; // Israel -> Asia/Jerusalem
extern const extended::ZoneInfo& kZoneJamaica; // Jamaica -> America/Jamaica
extern const extended::ZoneInfo& kZoneJapan; // Japan -> Asia/Tokyo
extern const extended::ZoneInfo& kZoneKwajalein; // Kwajalein -> Pacific/Kwajalein
extern const extended::ZoneInfo& kZoneLibya; // Libya -> Africa/Tripoli
extern const extended::ZoneInfo& kZoneMexico_BajaNorte; // Mexico/BajaNorte -> America/Tijuana
extern const extended::ZoneInfo& kZoneMexico_BajaSur; // Mexico/BajaSur -> America/Mazatlan
extern const extended::ZoneInfo& kZoneMexico_General; // Mexico/General -> America/Mexico_City
extern const extended::ZoneInfo& kZoneNZ; // NZ -> Pacific/Auckland
extern const extended::ZoneInfo& kZoneNZ_CHAT; // NZ-CHAT -> Pacific/Chatham
extern const extended::ZoneInfo& kZoneNavajo; // Navajo -> America/Denver
extern const extended::ZoneInfo& kZonePRC; // PRC -> Asia/Shanghai
extern const extended::ZoneInfo& kZonePacific_Johnston; // Pacific/Johnston -> Pacific/Honolulu
extern const extended::ZoneInfo& kZonePacific_Midway; // Pacific/Midway -> Pacific/Pago_Pago
extern const extended::ZoneInfo& kZonePacific_Ponape; // Pacific/Ponape -> Pacific/Pohnpei
extern const extended::ZoneInfo& kZonePacific_Saipan; // Pacific/Saipan -> Pacific/Guam
extern const extended::ZoneInfo& kZonePacific_Samoa; // Pacific/Samoa -> Pacific/Pago_Pago
extern const extended::ZoneInfo& kZonePacific_Truk; // Pacific/Truk -> Pacific/Chuuk
extern const extended::ZoneInfo& kZonePacific_Yap; // Pacific/Yap -> Pacific/Chuuk
extern const extended::ZoneInfo& kZonePoland; // Poland -> Europe/Warsaw
extern const extended::ZoneInfo& kZonePortugal; // Portugal -> Europe/Lisbon
extern const extended::ZoneInfo& kZoneROC; // ROC -> Asia/Taipei
extern const extended::ZoneInfo& kZoneROK; // ROK -> Asia/Seoul
extern const extended::ZoneInfo& kZoneSingapore; // Singapore -> Asia/Singapore
extern const extended::ZoneInfo& kZoneTurkey; // Turkey -> Europe/Istanbul
extern const extended::ZoneInfo& kZoneUCT; // UCT -> Etc/UTC
extern const extended::ZoneInfo& kZoneUS_Alaska; // US/Alaska -> America/Anchorage
extern const extended::ZoneInfo& kZoneUS_Aleutian; // US/Aleutian -> America/Adak
extern const extended::ZoneInfo& kZoneUS_Arizona; // US/Arizona -> America/Phoenix
extern const extended::ZoneInfo& kZoneUS_Central; // US/Central -> America/Chicago
extern const extended::ZoneInfo& kZoneUS_East_Indiana; // US/East-Indiana -> America/Indiana/Indianapolis
extern const extended::ZoneInfo& kZoneUS_Eastern; // US/Eastern -> America/New_York
extern const extended::ZoneInfo& kZoneUS_Hawaii; // US/Hawaii -> Pacific/Honolulu
extern const extended::ZoneInfo& kZoneUS_Indiana_Starke; // US/Indiana-Starke -> America/Indiana/Knox
extern const extended::ZoneInfo& kZoneUS_Michigan; // US/Michigan -> America/Detroit
extern const extended::ZoneInfo& kZoneUS_Mountain; // US/Mountain -> America/Denver
extern const extended::ZoneInfo& kZoneUS_Pacific; // US/Pacific -> America/Los_Angeles
extern const extended::ZoneInfo& kZoneUS_Samoa; // US/Samoa -> Pacific/Pago_Pago
extern const extended::ZoneInfo& kZoneUTC; // UTC -> Etc/UTC
extern const extended::ZoneInfo& kZoneUniversal; // Universal -> Etc/UTC
extern const extended::ZoneInfo& kZoneW_SU; // W-SU -> Europe/Moscow
extern const extended::ZoneInfo& kZoneZulu; // Zulu -> Etc/UTC


//---------------------------------------------------------------------------
// Unsupported zones: 0
//---------------------------------------------------------------------------



//---------------------------------------------------------------------------
// Inaccurate zones: 0
//---------------------------------------------------------------------------



//---------------------------------------------------------------------------
// Unsupported links: 0
//---------------------------------------------------------------------------



//---------------------------------------------------------------------------
// Notable links: 0
//---------------------------------------------------------------------------



}
}

#endif
