# See https://github.com/bxparks/EpoxyDuino for documentation about this
# Makefile to compile and run Arduino programs natively on Linux or MacOS.

CPPFLAGS := -D ACE_TIME_EXTENDED_ZONE_PROCESSOR_DEBUG=1
APP_NAME := DebugZoneProcessor
ARDUINO_LIBS := AUnit AceCommon AceTime AceSorting
include ../../../EpoxyDuino/EpoxyDuino.mk
