# See https://github.com/bxparks/EpoxyDuino for documentation about this
# Makefile to compile and run Arduino programs natively on Linux or MacOS.

APP_NAME := ExtendedZoneProcessorTransitionTest
ARDUINO_LIBS := AUnit AceCommon AceTime
DEPS := EuropeLisbon.h EuropeLisbon.cpp
include ../../../EpoxyDuino/EpoxyDuino.mk
