// This file was generated by the following script:
//
//   $ /home/brian/src/AceTimeTools/src/acetimetools/tzcompiler.py
//     --input_dir /home/brian/src/AceTime/src/zonedbctesting/tzfiles
//     --output_dir /home/brian/src/AceTime/src/zonedbctesting
//     --tz_version 2023c
//     --action zonedb
//     --language arduino
//     --scope complete
//     --db_namespace zonedbctesting
//     --include_list include_list.txt
//     --nocompress
//     --start_year 1980
//     --until_year 10000
//
// using the TZ Database files
//
//   africa
//   antarctica
//   asia
//   australasia
//   backward
//   etcetera
//   europe
//   northamerica
//   southamerica
//
// from https://github.com/eggert/tz/releases/tag/2023c
//
// Supported Zones: 16 (15 zones, 1 links)
// Unsupported Zones: 580 (335 zones, 245 links)
//
// Original Years:  [1844,2087]
// Generated Years: [1945,2087]
// Estimator Years: [1945,2090]
// Max Buffer Size: 7
//
// Records:
//   Rules: 227
//   Policies: 12
//   Eras: 30
//   Infos: 16
//
// Memory (8-bits):
//   Rules: 16
//   Rules: 2724
//   Policies: 36
//   Eras: 450
//   Zones: 195
//   Links: 13
//   Registry: 32
//   Formats: 92
//   Letters: 23
//   Fragments: 0
//   Names: 260 (original: 260)
//   TOTAL: 3841
//
// Memory (32-bits):
//   Rules: 24
//   Rules: 2724
//   Policies: 96
//   Eras: 600
//   Zones: 360
//   Links: 24
//   Registry: 64
//   Formats: 92
//   Letters: 33
//   Fragments: 0
//   Names: 260 (original: 260)
//   TOTAL: 4277
//
// DO NOT EDIT

#ifndef ACE_TIME_ZONEDBCTESTING_ZONE_REGISTRY_H
#define ACE_TIME_ZONEDBCTESTING_ZONE_REGISTRY_H

#include <zoneinfo/infos.h>

namespace ace_time {
namespace zonedbctesting {

// Zones
const uint16_t kZoneRegistrySize = 15;
extern const complete::ZoneInfo* const kZoneRegistry[15];

// Zones and Links
const uint16_t kZoneAndLinkRegistrySize = 16;
extern const complete::ZoneInfo* const kZoneAndLinkRegistry[16];

}
}
#endif
