# See https://github.com/bxparks/UnixHostDuino for documentation about this
# Makefile to compile and run Arduino programs natively on Linux or MacOS.

APP_NAME := SystemClockTest
ARDUINO_LIBS := AUnit AceCommon AceTime AceRoutine
include ../../../UnixHostDuino/UnixHostDuino.mk
