# See https://github.com/bxparks/EpoxyDuino for documentation about this
# Makefile to compile and run Arduino programs natively on Linux or MacOS.

APP_NAME := SystemClockTest
ARDUINO_LIBS := AUnit AceCommon AceTime AceRoutine
include ../../../EpoxyDuino/EpoxyDuino.mk
