# See https://github.com/bxparks/EpoxyDuino for documentation about this
# Makefile to compile and run Arduino programs natively on Linux or MacOS.

APP_NAME := HelloSystemClockCoroutine
ARDUINO_LIBS := AceCommon AceTime AceRoutine
include ../../../EpoxyDuino/EpoxyDuino.mk
