# See https://github.com/bxparks/UnixHostDuino for documentation
# about using UnixHostDuino to compile and run AUnit tests natively on Linux or
# MacOS.

APP_NAME := HelloSystemClockCoroutine
ARDUINO_LIBS := AceTime AceRoutine
include ../../../UnixHostDuino/UnixHostDuino.mk
