# See https://github.com/bxparks/UnixHostDuino for documentation about this
# Makefile to compile and run Arduino programs natively on Linux or MacOS.

APP_NAME := HelloSystemClockCoroutine
ARDUINO_LIBS := AceTime AceRoutine
include ../../../UnixHostDuino/UnixHostDuino.mk
