# See https://github.com/bxparks/UnixHostDuino for documentation about this
# Makefile to compile and run Arduino programs natively on Linux or MacOS.

APP_NAME := ZoneProcessorCacheTest
ARDUINO_LIBS := AUnit AceTime
include ../../../UnixHostDuino/UnixHostDuino.mk
