# See https://github.com/bxparks/AUnit/tree/develop/unitduino for documentation
# about using unitduino to compile and run AUnit tests natively on Linux or
# MacOS.

APP_NAME := TimeKeeperTest
ARDUINO_LIBS := AceTime AceRoutine
include ../../../AUnit/unitduino/unitduino.mk
