TARGETS := zone_infos.cpp zone_infos.h zone_policies.cpp zone_policies.h

all:
	../../../../tools/tzcompiler.sh --tag 2018g --action zonedb --language arduino --scope extended --db_namespace zonedbx2018g --start_year 2000 --until_year 2050
