#!/usr/bin/env bash
#
# Copyright 2018 Brian T. Park
#
# MIT License
#
# Shell script wrapper around tzcompiler.py. The main purpose is to run 'git
# checkout' on the TZ Database repository (located at $PWD/../../tz) to retrieve
# the TZ version specified by the (--tag). It then runs the tzcompiler.py
# script to process the zone files. The location of the TZ Database is passed
# into the tzcompiler.py using the --input_dir flag. The various 'validation_*'
# files are produced in the directory specified by the --output_dir flag.
#
# Usage:
#
#   $ tzcompiler.sh --tag {tag}
#       --action (zonedb|zonelist|validate)
#       --language (python|arduino)
#       --scope (basic|extended)
#       [other flags...]
#
# There are 3 high-level modes of this script, depending on the --action flag:
#
#   * zonedb
#       * Generate the 'validation_data.{h,cpp}' and 'valiation_tests.cpp' files
#       needed by the Arduino tests in ace_time/tests/validation/*.
#   * zonelist
#       * Generate the 'zones.txt' file which contains the list of Zone names
#       which are supported by the given --language and --scope.
#   * validate
#       * Run the Validator to compare the test data generated by
#       TestDataGenerator (using pytz) and the calculations of the ZoneSpecifier
#       Python class.
#
# Examples:
#
#   $ tzcompiler.sh --tag 2018i --action zonedb --language arduino \
#           --scope basic
#       * generates zone*.{h,cpp} files in the current directory
#
#   $ tzcompiler.sh --tag 2018i --action zonedb --language arduino \
#           --scope extended
#       * generates extended zone*.{h,cpp} files in the current directory
#
#   $ tzcompiler.sh --tag 2018i --action zonedb --language python \
#           --scope extended
#       * generates zone*.py files in the current directory
#
#   $ tzcompiler.sh --tag 2018i --action validate --language python \
#           --scope basic
#       * validate the internal zone_info and zone_policies data
#
#   $ tzcompiler.sh --tag 2018i --action validate --language arduino \
#           --scope basic
#       * validate the internal zone_info and zone_policies data
#
# Flags
#
# Flags which are not recognized by this script are passed directly into
# the tzcompile.py script for further processing. Some examples are:
#
#   Transformer:
#
#       --start_year
#           Retain TZ information since this year (default 2000).
#       --granularity
#           Retain time value fields in seconds (default 900)
#       --strict
#           Remove zone and rules not aligned at time granularity.
#
#   Validator:
#       --validate
#           Validate the zone_infos and zone_policies. Implies activation
#           of both --validate_buffer_size and --validate_test_data.
#       --validate_dst_offset
#           Optional flag to tell Validator to validate DST offsets as well as
#           the total UTC offset and datetime components. This option causes
#           many false positives, seemingly due to bugs in pytz.

set -eu

# Can't use $(realpath $(dirname $0)) because realpath doesn't exist on MacOS
DIRNAME=$(dirname $0)

# Point to the TZ git repository, assumed to be a sibling of AceTime repository.
INPUT_DIR=$DIRNAME/../../tz

# Output generated code to the current directory
OUTPUT_DIR=$PWD

function usage() {
    echo 'Usage: tzcompiler.sh --tag tag --action (zonedb|validate|zonelist)'
    echo '      --language (python|arduino) --scope (basic|extended)'
    echo '      [...other python_flags...]'
    exit 1
}

pass_thru_flags=''
tag=''
while [[ $# -gt 0 ]]; do
    case $1 in
        --tag) shift; tag=$1 ;;
        --help|-h) usage ;;
        -*) break ;;
        *) break ;;
    esac
    shift
done
if [[ "$tag" == '' ]]; then
    usage
fi

echo "\$ pushd $INPUT_DIR"
pushd $INPUT_DIR

echo "\$ git checkout $tag"
git checkout $tag

echo '$ popd'
popd

echo \$ $DIRNAME/tzcompiler.py \
    --input_dir $INPUT_DIR \
    --output_dir $OUTPUT_DIR \
    --tz_version $tag \
    $@
$DIRNAME/tzcompiler.py \
    --input_dir $INPUT_DIR \
    --output_dir $OUTPUT_DIR \
    --tz_version $tag \
    "$@"

echo "\$ pushd $INPUT_DIR"
pushd $INPUT_DIR

echo '$ git checkout master'
git checkout master

echo '$ popd'
popd
