TARGETS := zonedb zonedbx zonedbc tzonedb tzonedbx tzonedbc

.PHONY: $(TARGETS) zonedbs

zonedbs: $(TARGETS)

zonedb:
	$(MAKE) -C $@

zonedbx:
	$(MAKE) -C $@

zonedbc:
	$(MAKE) -C $@

tzonedb:
	$(MAKE) -C $@

tzonedbx:
	$(MAKE) -C $@

tzonedbc:
	$(MAKE) -C $@
