TARGETS := zonedb zonedbx zonedbc zonedbtesting zonedbxtesting zonedbctesting

.PHONY: $(TARGETS) zonedbs

zonedbs: $(TARGETS)

zonedb:
	$(MAKE) -C $@

zonedbx:
	$(MAKE) -C $@

zonedbc:
	$(MAKE) -C $@

zonedbtesting:
	$(MAKE) -C $@

zonedbxtesting:
	$(MAKE) -C $@

zonedbctesting:
	$(MAKE) -C $@
