TARGETS := zonedb zonedbx zonedbc testingzonedb testingzonedbx testingzonedbc

.PHONY: $(TARGETS) zonedbs

zonedbs: $(TARGETS)

zonedb:
	$(MAKE) -C $@

zonedbx:
	$(MAKE) -C $@

zonedbc:
	$(MAKE) -C $@

testingzonedb:
	$(MAKE) -C $@

testingzonedbx:
	$(MAKE) -C $@

testingzonedbc:
	$(MAKE) -C $@
