name: AUnit Tests

on: [push]

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2

    - name: Setup
      run: |
        cd ..
        git clone https://github.com/bxparks/EpoxyDuino
        git clone https://github.com/bxparks/AceButton
        git clone https://github.com/bxparks/AceRoutine
        git clone https://github.com/bxparks/AUnit
        git clone https://github.com/bxparks/AceCommon

    - name: Verify examples
      run: |
        make -C examples

    - name: Verify tests
      run: |
        make -C tests
        make -C tests runtests
