name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-18.04
    
    steps:
    - uses: actions/checkout@v1

    - name: Setup
      run: |
        cd ..
        git clone https://github.com/bxparks/UnixHostDuino
        git clone https://github.com/bxparks/AceButton
        git clone https://github.com/bxparks/AceRoutine
        git clone https://github.com/bxparks/AUnit
    - name: Verify examples
      run: |
        make -C examples clean
        make -C examples
    - name: Verify tests
      run: |
        make -C tests clean
        make -C tests
        make -C tests runtests
